### ISSUE TITLE
explorer crashes attempting Value -> TupleValue cast

### ISSUE THREAD

**Issue by pk19604014** [carbon-language/carbon-lang#1394]
````
// Generated by proto_to_carbon.

package EmptyIdentifier impl;

fn apply[T:! Type, U:! Type](f: T, EmptyIdentifier: U)
{
match (true[true]) {}
}

fn EmptyIdentifier() -> apply(true, true);

fn Main() -> i32 {
  return 0;
}

explorer: external/llvm-project/llvm/include/llvm/Support/Casting.h:566: decltype(auto) llvm::cast(const From &) [To = Carbon::TupleValue, From = Carbon::Value]: Assertion `isa<To>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

**Comment by jonmeow** [comment]
To note, since a different approach of rearranging type-checking in explorer is being suggested, a test-case to verify:

```
class Foo {
  fn PickType() -> Type { return i32; }
  // Invalid because the body of PickType should be moved below Foo:
  fn GetZero() -> PickType() { return 0; }
}
```

I believe this is invalid due to proposal #875, because the body of PickType should only be type-checked after Foo is complete; consequently, it can't be used to determine the return type of GetZero, because that must be type-checked in order to complete Foo.

I don't think explorer had previously been set up to do this, so it's just an edge case to watch for.
