### ISSUE TITLE
Carbon spec and the reference compiler should be in two different repos

### ISSUE THREAD

**Issue by apinski-cavium** [carbon-language/carbon-lang#1426]
The spec and the reference compiler should be in two different repos to allow other front-ends to be created without having to deal with the reference compiler. for an example someone might go in and create a new front-end which targets GCC generic IR rather and having the reference compiler in the same repo can cause many other issues there too.

**Comment by chandlerc** [comment]
So far, we've prioritized keeping things together and fast-moving with a single repo.

We can look at splitting later if it becomes important. But I think we'd also want to look at other approaches such as creating easy ways to extract / mirror specific parts for users that want a narrow view.

Anyways, not sure this is something we really want to spend a bunch of time iterating on in the super short term.

**Comment by zygoloid** [comment]
I agree, revisiting this doesn't seem like a high priority right now. We can reconsider if we do have out-of-tree implementations and the current approach turns out to be a problem in practice -- I'd hope that read-only access to our specification (eg, reading our rendered .md files online) should be enough for that most of the time, but maybe it won't be.
