### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by benthevining** [carbon-language/carbon-lang#1436]
CMake is the industry standard build system for C++ code, and if Carbon wants to advertise interoperability with C++, it seems very foolish not to support CMake out of the box.

It is possible to implement Carbon as a first-class language in CMake, or Carbon could provide a utility module with commands like `carbon_add_library()`, `carbon_add_executable()`, etc.

**Comment by atsushieno** [comment]
It will also help Android NDK integration, once toolchains are appropriately built. There is no Android Studio integration with Bazel (I'm saying Android Studio, not just Bazel console mobile builds that neither gives coding aid nor lldb integration).

**Comment by cloudhan** [comment]
If I have choice, I would avoid CMake as plague. Bazel is a much better than CMake. Since you are making choice (implicitly by opening an issue in the C++ successor repo), why not choose a better one?

**Comment by atsushieno** [comment]
Bazel has beautiful dependency management system (edit: *task* dependency) and the syntax would be definitely cleaner than CMake (I don't prefer CMake syntax eiher), but build system is not only about build script syntax. When it comes to IDE integration, CMake is supported almost everywhere, which means that you are most likely able to open those Carbon CMake projects on your IDE. Otherwise you have to start with implementing Bazel integration for each IDE.

Are there such IDE extensions already? Note that it is not only about running build commands. Expanding project contents into the IDEs.

At this state I rather assume that use of Bazel in current source tree does not necessarily mean "the Carbon build system" will be Bazel. Also, while sometimes one build system kinda has to be dominant (like MSBuild for most of dotnet project kinds), they do not necessarily have to be fixed to one. Having CMake as an option works for us.

**Comment by benthevining** [comment]
CMake is a de facto industry standard for C++. It doesn't really matter if Bazel is better than CMake or not (which I don't believe it is), what matters is that CMake support is much more _useful_ than Bazel.

**Comment by chandlerc** [comment]
Just to be clear, while we are using Bazel to build the Carbon project, there is no expectation of that being the only (or even primary) build system *for Carbon code*.

We're a long way from it making sense to try to have upstream build system support (or even *any* build system support) for Carbon code, but when we get there, we should definitely consider *all* the major build systems relevant to C++ developers: CMake, Automake, Makefiles, Bazel, Gradle, ....

For now, not sure its useful to keep an issue open for this so closing.

**Comment by benthevining** [comment]
Thanks for the clarification!
