### ISSUE TITLE
Stupid Syntax

### ISSUE THREAD

**Issue by dexception** [carbon-language/carbon-lang#1446]
Stop this project. It is a waste of time. 

C# is the successor of C++.

**Comment by Narnillian** [comment]
Exactly how long has C# been *about* to surpass C++?

**Comment by ZbigniewRA** [comment]
C# is a fine language. If it can be used for a project, it would be a good choice.

However C# has design decisions that make it unsuitable for some kinds of projects. For example:
- garbage collector cannot be used for performance critical code (due to overheads and unpredictability),
- C# has additional runtime overheads, like reflection, which are not an option for memory constrained systems,
- interoperation with C++ is not seamless,

As for the syntax itself: it can be alien at first, as any new thing is, but won't be a surprise for someone familiar with other languages designed in the last 20 years.

**Comment by deimsdeutsch** [comment]
@atsushieno C# can also run without GC. Stop repeating the same thing ! 
If carbon is to be the true successor of C++ it has to better C# which right now is looking like a complete joke.

**Comment by Natalie-Skalicka** [comment]
> @atsushieno C# can also run without GC. Stop repeating the same thing ! If carbon is to be the true successor of C++ it has to better C# which right now is looking like a complete joke.

It still needs to run in CLR and be interpreted, That costs overhead and cycles. Stop making fool out of yourself. 

C# is fine, but not so much for performance and critical projects. Or anything that's lower level than two levels of abstraction i believe so

**Comment by atsushieno** [comment]
I don't think you really understand what "no GC" really means for those VM-based languages. Show me any single practical application (beyond mere example code) that keeps creating new object instances while running for significantly long time with GC=None.

**Comment by OlaFosheimGrostad** [comment]
Carbon looks like a nice project, but please reconsider the syntax. You will not be able to get C++ programmers onboard by having things like "fn", "var" and why on earth are you using CamelCase in the standard library? I want my programs to be clean and reserve camel case for domain specific types and use lower case for ADTs and domain-agnostic libraries.

Also, get some usability experts involved. Most programmers are not very good at it. For instance, the function signature is failing basic usability criteria, by ending up looking like this (from README.md):

```
fn Patition[T:! Comparable & Movable](s: Slice(T)) -> i64
```

The brackets ([]) makes no sense here, they should be reserved for indexing/indexable entities. It also obscures the formal parameters by pushing it far to the right.  The constraints on T are less important than the formal arguments, so you should be able to have them on their own line below the signature. This can be deduced from basic usability principles.

Regarding parsing: as we we  see "->" is sufficient for determining that this is a function signature. There is no need for "fn", this is just extra line noise. Let the IDE render function signatures in a way that makes them stand out (or even add a fn icon, if you want it). Don't limit yourself to a 1970s syntax just because you start out with flex/bison. You have to make an appeal to the existing C++ culture here, so let the IDE tune the "iconography" to different audiences. You should not try to appeal to ML/Rust users… that makes no sense.

**Comment by atsushieno** [comment]
Using `[...]` for generics is a modern design choice. https://soc.me/languages/stop-using-angle-brackets-for-generics.html

**Comment by OlaFosheimGrostad** [comment]
> Using `[...]` for generics is a modern design choice. 

Subjective opinions about «modernity» is neither a usability argument nor a semiotic argument, and «modern» is certainly not a valid quality assessment rationale.

*Consistency* is a usability argument.

*Familiarity* is a semiotic argument.

I am a big fan of Modernism, but confusing semiotics is not Modernism, it is Post-Modernism. ;-)

**Comment by atsushieno** [comment]
I thought the linked blog post explained all logical reasoning behind preferring `[]` over `<>`. I would highly recommend to actually read whatever provided by others. They are usually relevant and useful materials.

**Comment by mihail-8480** [comment]
> > @atsushieno C# can also run without GC. Stop repeating the same thing ! If carbon is to be the true successor of C++ it has to better C# which right now is looking like a complete joke.
> 
> It still needs to run in CLR and be interpreted, That costs overhead and cycles. Stop making fool out of yourself.
> 
> C# is fine, but not so much for performance and critical projects. Or anything that's lower level than two levels of abstraction i believe so

It doesn't have to run in the CLR and be interpreted tho, you can use NativeAOT (which will be a .net 7 feature, it's currently in the preview versions.)

It might not beat C++ in performance, but with NativeAOT it might match it in the future.

**Comment by jonmeow** [comment]
If C# works for you, you absolutely should! There are pros and cons to the language though, and due to the GC choices it doesn't work for everyone (https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#why-not-a-garbage-collected-language-like-java-kotlin-or-go).

However, one thing I want to be clear on is we want Carbon to be a kind community. Criticizing Carbon is fine: there are areas where the syntax can be improved, and certainly some choices won't make everyone happy. However, we need to be thoughtful about how we do it. Calling ideas "stupid" is the wrong way; if you want to say you don't like it, just say "I don't like it." https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md

While some people on this thread have made reasonable criticisms, due to the overall tone of this thread, we're closing and locking it.

**Comment by chandlerc** [comment]
We've gone through this thread and are going to delete it as it both violates the CoC and doesn't seem to have important content to preserve.
