### ISSUE TITLE
Ambiguities in the grammar

### ISSUE THREAD

**Issue by mingodad** [carbon-language/carbon-lang#1450]
Trying to create an `LL(1)` parser with https://mingodad.github.io/CocoR-Typescript (and family) I found that this definition is problematic:
```
sized_type_literal    [iuf][1-9][0-9]*
```
It's ambiguous with this:
```
identifier            [A-Za-z_][A-Za-z0-9_]*
```
So when we see something like shown bellow, both rules apply and without context sensitive parsing/lexing how to know if they are identifiers or sized_type_literals ?
```
i3 || u4 || f5
```
I would prefer to have it postfixed like:
```
sized_type_literal   [1-9][0-9]*  [iuf]
```

_Originally posted by @mingodad in https://github.com/carbon-language/carbon-lang/issues/1423#issuecomment-1189458076_

**Comment by mingodad** [comment]
Also another one is `struct_literal` and `struct_type_literal` both allow `{}` (empty open/close curly braces), how to distinguish which is which in such cases ?

**Comment by mingodad** [comment]
It seems that this repository is not correctly synced because we have in https://github.com/carbon-language/carbon-lang/blob/trunk/third_party/examples/re2/re2.carbon this declaration:
```
private interface Parse4ary;
```
But there isn't any token `private` on the lexer/grammar .

**Comment by mingodad** [comment]
Also in the same `re2.carbon` there is this declarations that doesn't exists in the grammar:
```
class RE2 {
  // We convert user-passed pointers into special Arg objects
  class Arg; //////!!!!! not in the grammar forward declaration
  class Options; //////!!!!! not in the grammar forward declaration

  // Defined in set.h.
  class Set; //////!!!!! not in the grammar forward declaration
...
```

**Comment by jonmeow** [comment]
> So when we see something like shown bellow, both rules apply and without context sensitive parsing/lexing how to know if they are identifiers or sized_type_literals ?
> 
> ```
> i3 || u4 || f5
> ```

`i3`, `u4`, and `f5` are all reserved as type keywords. This is reflected in how trying to compile `var i3: auto = 3;` is an error in the Carbon Language explorer today: https://carbon.compiler-explorer.com/z/b9soTzrTh

Note that all keywords look like valid identifiers. The type literal keywords are no different in this sense. (https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/lexical_conventions/words.md)

> I would prefer to have it postfixed like:

The format was chosen on https://github.com/carbon-language/carbon-lang/issues/543, influenced by matching Rust (https://doc.rust-lang.org/reference/types/numeric.html). I think we wouldn't have chosen a postfix letter because it would easily be confused visually with numeric literals. In particular, `32.f` is a valid value in C++.

> Also in the same re2.carbon there is this declarations that doesn't exists in the grammar:

re2.carbon is a thought experiment. It can be considered to be reflective of the direction, not something that is currently implemented.

**Comment by mingodad** [comment]
Thank you for reply !
It's a bit confusing because if they are types it's strange that they appear as `primary_expression`.

**Comment by jonmeow** [comment]
I'm thinking through where your confusion may be, and maybe it's the mixing of types and expressions (which I think differs slightly from C++).

In Carbon, types like String are types, but they're also an instance of the Type object (`var x: Type = i32;` is valid). In `var x: i32 = 3;`, I think it's clear that `3` is an expression, but so is `i32`. We would typically call `i32` a "type expression" just because it's an expression that at compile-time can be determined to be a type.

Similarly, if we had some `var x: GetType() = 3;` that could be valid too if `GetType()` could be evaluated at compile time to return a type. 

Does that help address your confusion? If not, could you describe what you find strange?

**Comment by mingodad** [comment]
Thanks again for reply !
Well as you've described it's different from C++ and maybe I will not be the only one to be confused with this, I can grasp `i32` as type but as expression that is new, would it be less confusing if they were clearly separated/labeled in the grammar using a term like you've used `type_expression` separated from `primary_expression` ?

Any way it seems that `Carbon` has it's own new bag of tricks and should be viewed that way (maybe when there is a working version with tangible examples I'll revisit it).

Cheers !

**Comment by chandlerc** [comment]
> Thanks again for reply ! Well as you've described it's different from C++ and maybe I will not be the only one to be confused with this, I can grasp `i32` as type but as expression that is new, would it be less confusing if they were clearly separated/labeled in the grammar using a term like you've used `type_expression` separated from `primary_expression` ?

We can't fully separate them, they really are the same grammar.

For example, we expect parameterized types (like `std::vector<int64_t>` in C++) to use function call syntax at a fundamental level (maybe `Vector(i64)`, although none of the names here are decided).

> Any way it seems that `Carbon` has it's own new bag of tricks and should be viewed that way (maybe when there is a working version with tangible examples I'll revisit it).
> 
> Cheers !

We do have a working Bison grammar in the explorer if useful.

Anyways, is there anything else we can do to help here?

**Comment by jonmeow** [comment]
I'm closing this issue because I think the questions were answered. Let me know if there's something I'm missing and we can reopen.
