### ISSUE TITLE
Have mandatory braces, no parenthesis in the if/for/while syntax

### ISSUE THREAD

**Issue by laurentlb** [carbon-language/carbon-lang#1462]
The [if/else](https://github.com/jonmeow/carbon-lang/blob/trunk/proposals/p0285.md) proposal mentions two alternatives at the end: "No parentheses" and "Require braces". The conclusion was:

> The benefits of this are debatable, and it should be examined by an advocate in a focused proposal. For now, we should match C++'s decision.

I would like to discuss the topic a bit more.

* In C++, braces after a `if` are optional. In practice, many style guides require the use of braces, e.g. https://google.github.io/styleguide/cppguide.html#Conditionals
* Giving the choice of having braces doesn't seem useful, if style guides are likely to discourage it. It also conflicts with the [One Way Principle](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/one_way.md).
* Making braces mandatory allows us to remove the parenthesis around the expression:

```c++
if x {
  do_parse = false;
}
```

* Parenthesis are already used in lots of different places in the grammar: function calls, precedence, generics... Removing parenthesis here can reduce the overloading.
* This idea has been successfully used in other languages (e.g. Go), and probably won't disrupt people familiar with C++ (if they put the parenthesis after a if, they would just be useless).
* Removing the parenthesis would be more consistent with the [Conditional expressions](https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0911.md) syntax (`if cond then x else y`).

For consistency, the syntax of `while` and `for` would need to be updated as well:

```c++
while x { ... }

for var i : mylist { ... }
```

**Comment by Turbine1991** [comment]
I don't think this will solve any usability issues. However it may contribute to people writing less readable code. I've learnt that giving syntax freedom leads to people doing to bare minimum to get by.

Though I quite like this suggestion. 😅 I'm a pessimist.

**Comment by zygoloid** [comment]
Braces in `if` etc. are mandatory in Carbon: the rule from the if/else proposal was altered by [p0623](https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0623.md#proposal).

Rust's choice to have optional parentheses around the condition leads to grammar problems, because Rust also has expression syntaxes comprising an expression followed by another expression.  For example, the Rust compiler rejects this because of the braces at the top level in the condition:
```
struct A { n: bool }

fn main() {
    if A{n: true}.n {}
}
```
We don't have expression syntaxes like this just yet, but it seems likely that we will want to consider such syntaxes at some point, so there's a significant risk of this approach creating grammar issues for Carbon too.

**Comment by chandlerc** [comment]
I agree with @zygoloid here. Moreover, I think this also indicates when is the optimal time to revisit this -- when we feel like the expression grammar and `if` grammar are both quite complete, we could much more realistically see if there is an unambiguous option here, but for now, we should stick with the `()`s. Leads seem aligned here so marking this as decided.

**Comment by laurentlb** [comment]
Thanks a lot for the explanation!
