### ISSUE TITLE
Please consider switching the keyword shorthand "fn" to "function"

### ISSUE THREAD

**Issue by Turbine1991** [carbon-language/carbon-lang#1470]
Hi,
I've used a good variety of languages throughout my 17 year career, so I'm used to picking up new keywords and syntax.

Consider how JavaScript allows functions to be declared by the keyword "function". Easy to read, easy to remember.

Let's extend the keyword naming logic of "fn" to return "rn". There's a decrease of legibility and the language becomes less intuitive.

Languages like Rust tend to overuse shorthand to the point it hinders your recollection of the shorthand required and decreases legibility. Think of an if else statement, some use elif or ifel instead of just using an "else if" statement. Some needless Rust shorthand "impl = implements", "pub = public". One does not write this enough times for a few extra characters to be a problem. Python's "def" would really throw C++ devs off.

I'm just hoping for more sensibly written code. A good use of commonly used unambiguous shorthand is async instead of asynchronous.

--
Allowing both would be an acceptable compromise if fn must remain.

**Comment by 0x08088405** [comment]
> Consider how JavaScript allows functions to be declared by the keyword "function". Easy to read, easy to remember.

Yeah, maybe if your project is targeting pre-ES2015.

**Comment by jonmeow** [comment]
I've hidden the comment above. Please don't use sarcasm to make points. In Carbon Language's forums, we want to keep discussion kind and polite. https://github.com/carbon-language/carbon-lang/blob/trunk/CODE_OF_CONDUCT.md

**Comment by jonmeow** [comment]
I'll leave this for a lead, but I do want to note:

- The `fn` keyword tradeoffs that were considered are documented at: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0438.md#function-keyword (clarity was included)
- We probably wouldn't provide multiple keywords for this; we favor one way of doing things: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/one_way.md

**Comment by yanwuguangjun** [comment]
agree

**Comment by yanwuguangjun** [comment]
“func”    is  a   compromise plan  esay to  understand  an   esay to read

**Comment by jaykrell** [comment]
Less ambiguous more verbose plain text search is desirable, "function foo".

**Comment by Turbine1991** [comment]
> I'll leave this for a lead, but I do want to note:
> 
> * The `fn` keyword tradeoffs that were considered are documented at: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0438.md#function-keyword (clarity was included)
> * We probably wouldn't provide multiple keywords for this; we favor one way of doing things: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/one_way.md

Interesting read, it looks like you've debated everything internally.

Though function as the longest derivative is not necessarily a huge con, especially when it's not expected to be used line after line. Readability ought to be prioritised over shorthand where possible. Such shorthand, if further employed - could inevitably tarnish the vision of a considerably more maintainable C++. :(

**Comment by slerpyyy** [comment]
The main argument here seems to be that `fn` is difficult to understand without context, though the keyword cannot be used without context.

Consider the keywords `break` or `continue`. If these keywords were shortened to something like `brk` and `ctn`, it would be difficult to guess what these keywords are referring to, especially when you're reasoning about code locally in a gigantic loop, because you have very little to go off of.

The `return` keyword is already better because you usually give it a value. If you are in a function that returns an integer and you see `rtn 5;` with no code afterward in that control flow branch, you might be able to guess what it does.

The `for` keyword is also interesting because the keyword itself barely gives you anything. You can't read the keyword on its own and figure out that it's a loop, but there is so much context around it and it's such a common keyword that you don't even think about how weird it is.

The `fn` keyword is surrounded by so much context that it is entirely unnecessary. If you read something like
```
Square(x: i32) -> i32 {
  return x * x;
}
```
you can almost certainly tell what this is doing without a keyword that spells out "this is a function declaration".

The only reason we have this keyword in the first place is to help the parser figure out that a function declaration is coming up and to provide a grounding strategy to recover from syntax errors. (Having a keyword like this has the nice side effect that you can substring search "fn \<function-name\>" to find the declaration in simple text editors).

So naturally, since this keyword barely carries any meaning, we want it to be as short and easy to type as possible which makes `fn` a great choice.

**Comment by slerpyyy** [comment]
> Python's "def" would really throw C++ devs off.

I'm also seeing the point that programmers are either unwilling or unable to learn new keywords which I find hard to defend.

A programmer going from C++ to Python has to get used to a completely different type system, reference semantics, garbage collection, immutable strings, different iterator semantics and lack of mutability control and proper class destructures, but it is the `def` keyword that throws them off?

Is there any evidence that points toward the `def` keyword being too cryptic and hindering the learning progress for beginners?

I am willing to challenge this assumption, but I am happy to be proven wrong.

**Comment by jaykrell** [comment]
`def`: I tried to learn Go, etc. type/name are reversed, semicolon optional, loops reduced to just for, etc.
Each step sounds easy but it is death by a thousand cuts. Eventually it adds up and the entirely new language is hard to adjust to, hard to make so many simultaneous cosmetic isomorphic translations, at least rapidly at first. Eventually we will all forget C++, and new programmers will never learn it and none of this will matter. So it is a tough thing, between long term ideals and large short term transition. Beginners are probably the more flexible ones, fewer languages and less C++ to adapt from.
Teachability to beginners vs. teachability to C++ programmers may be opposites. :)

`fn` seems unnecessarily short to me, but I hadn't considered as much as others, like how columns line up in different formatting options and the nuances of fn/fun/func or consulting Rust community. The Carbon people were diligent.

**Comment by ltfschoen** [comment]
> The main argument here seems to be that `fn` is difficult to understand without context, though the keyword cannot be used without context.
> 
> Consider the keywords `break` or `continue`. If these keywords were shortened to something like `brk` and `ctn`, it would be difficult to guess what these keywords are referring to, especially when you're reasoning about code locally in a gigantic loop, because you have very little to go off of.
> 
> The `return` keyword is already better because you usually give it a value. If you are in a function that returns an integer and you see `rtn 5;` with no code afterward in that control flow branch, you might be able to guess what it does.
> 
> The `for` keyword is also interesting because the keyword itself barely gives you anything. You can't read the keyword on its own and figure out that it's a loop, but there is so much context around it and it's such a common keyword that you don't even think about how weird it is.
> 
> The `fn` keyword is surrounded by so much context that it is entirely unnecessary. If you read something like
> 
> ```
> Square(x: i32) -> i32 {
>   return x * x;
> }
> ```
> 
> you can almost certainly tell what this is doing without a keyword that spells out "this is a function declaration".
> 
> The only reason we have this keyword in the first place is to help the parser figure out that a function declaration is coming up and to provide a grounding strategy to recover from syntax errors. (Having a keyword like this has the nice side effect that you can substring search "fn <function-name>" to find the declaration in simple text editors).
> 
> So naturally, since this keyword barely carries any meaning, we want it to be as short and easy to type as possible which makes `fn` a great choice.

If the the parser can figure out that a function declaration is coming up by using a regular expression instead of a keyword search and the function keyword doesn't have any other meaning, then is there any further reason why we couldn't just omit using it at all? 

How would omitting it affect parser performance?

Don't most text editors allow you to search using regular expressions too? For example in VSCode i often search just using a regex. 

If they don't then doesn't that just presents an opportunity for the text editor to improve itself by adding a search by regex feature.

**Comment by jaykrell** [comment]
Consider an LL(1) parser? Leading keywords are great? :)
Also for editors, don't force people into regexps so quickly, constant strings are easier.

**Comment by ltfschoen** [comment]
> Consider an LL(1) parser? Leading keywords are great? :) Also for editors, don't force people into regexps so quickly, constant strings are easier.

Isn't it the case that many text editors allow you to choose to generate a code content template or import an existing code content template library for a specific language, so they wouldn't necessarily be forced to use regex to search?
So if they've imported the latest official Carbon code content template library it'd include a template for a generating a function template. So when inserting one they'd just specify things like the function name. Likewise maybe they could use the same template to search/filter for specific functions. They could create a GraphQL-like schema to represent a Carbon function, and then use that schema to write a query that provides the function name as the filter (see https://www.apollographql.com/blog/graphql/filtering/how-to-search-and-filter-results-with-graphql/)

**Comment by chandlerc** [comment]
Since as was pointed out, the decision to use `fn` did consider the alternatives here, I'm closing the issue. Not seeing any new information.

If folks have important new information to motivate revisiting this, they should probably create a PR with a proposal that writes up that rationale, and/or file a detailed question for leads with the specific rationale and new information that motivates revisiting.

For now, closing this to keep our issue discussions focused.

**Comment by fowles** [comment]
Carbon has grown by an order of magnitude since this decision was made.  While I personally, prefer `fn`, I think the leads should be open to broad strokes discussions like this that might not have fully formulated things (or might simply wish to revisist existing arguments).  Obviously, they should not revisit every decision whenever anyone disagrees with it, but I think a reasonable request is for any issue that is both

*  undergoing active discussion with real alternatives (not just I don't like X)
*  some change in the community (either an order of magnitude growth or exposure to a new industry segment)

then the leads should (at a reasonable schedule) investigate, discuss, and restate their rationale.

**Comment by chandlerc** [comment]
Yeah, thanks for pushing back here @fowles - it does seem reasonable to do a check-in with the leads here. Moving it onto their queue.

**Comment by malytomas** [comment]
It was already stated that the `fn` is intended for _programmers_, not for the parser, which could distinguish function even without any keyword. The purpose is to bring to attention that a significant separation in the code has happened. Otherwise the keyword could be removed completely.

However, the two-letter abbreviation does not fulfill that role:
- it is so short it can be easily overlooked
- it could be an abbreviation for many other words, which makes it ambiguous (to the programmer)
  - see https://acronyms.thefreedictionary.com/FN (53 meanings)
  - compare that with `var` https://acronyms.thefreedictionary.com/var (37 meanings) or `func` https://acronyms.thefreedictionary.com/func (2 meanings!)
- _it makes little to no break in the visual flow of the code, yet it makes one of the most significant breaks in the structure of the code_ (together with class/struct)
- some search engines do not allow to search for less than 3 or 4 letters
- your own discussion ( https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0438.md#function-keyword ) feels inconclusive:
  - you say that removing letters in the middle of a word is undesirable
  - you discuss code indentation, I would say that 2 spaces indentation is more common than 8 spaces indentation (but I do not know how to search github for that)
  - _`fn` is used in rust only, while `func` is used in two other more popular languages, and `function` is used in 5 languages_
  - the only arguments for the `fn` is that it is shorter, and the hungarian notation
- today, it should be easy to configure code editors to replace <f+n+space> with <function+space> automatically, alleviating the shortness argument

**Comment by davidzchen** [comment]
Some counterpoints:

> it could be an abbreviation for many other words, which makes it ambiguous (to the programmer)

I think this rationale makes the mistake of looking at the `fn` keyword solely in isolation and not in context. From the context, it is pretty obvious that it is shorthand for the word "function." Given how common function definitions are in the code, having a shorter keyword IMO is more ergonomic since it avoids the need to have to type so many characters for a very common keyword.

> some search engines do not allow to search for less than 3 or 4 letters

When people search for code, they generally search for things like variable names, function names, class names, etc. I am not convinced that searching for a particular keyword is a common or useful case since for instance, searching for "function" literally just gives you all of the function definitions in source files.

> fn is used in rust only, while func is used in two other more popular languages, and function is used in 5 languages

I think it is worth looking at the types of languages here:

* "fn" and "func" are used in Rust, Swift, and Go. These languages are most similar to Carbon, and in the case of Rust, arguably the major "competitor." These languages share similar use cases and characteristics (statically compiled, used for implementing large systems or native application code).
* "function" is used in not only JavaScript, MatLab, PHP, R, and TypeScript, but also Bash. These are scripting languages and are the least similar to Carbon in terms of characteristics and use case. Additionally, aside from TypeScript, these languages are quite old, and modern programming languages such as Rust, Swift, and Go have come a long way since the era where those languages were created. Additionally, the main reason why TypeScript uses "function" is that TS is meant to be a superset of JavaScript and is thus inherently tied to JavaScript patterns.

I think that it is important to consider the overall aesthetics of a language. Looking at the design of modern languages such as Rust, Kotlin, and Swift, I think we are moving away from the verbosity of languages from the past (in particular Java and C#), and I think that is a very good thing.

I am in favor of staying with Rust's convention of "fn". Given how popular Rust has become and is in fact [the most loved language](https://survey.stackoverflow.co/2022/#section-most-loved-dreaded-and-wanted-programming-scripting-and-markup-languages) on StackOverflow, I do not think that its use of "fn" or any of its other abbreviations really takes away from the developer experience in any way.

**Comment by ltfschoen** [comment]
> Given how common function definitions are in the code, having a shorter keyword IMO is more ergonomic since it avoids the need to have to type so many characters for a very common keyword.

I tend to use programming language-specific "auto-complete" plugins when using text editors and IDEs. 

When authoring code that'd require me to type an initial character like "f" and then it'd give me context-based suggestions, which could include choosing to let it just generate the word "fn" or "function", or choosing to generate an entire function template and next prompting me to enter the first argument and so forth so it could populate that automatically. 

If I were authoring code by voice rather than typing then I'd prefer to say an abbreviation like "fn" rather than "function" to generate a function template too, like in this example https://youtu.be/8SkdfdXWYaI?t=9m09s,  so I wouldn't lose my voice too quickly. 

But when reviewing code I don't always need to know the context, so I could recognise it's a function block just by seeing the pattern `[]() -> {}`. What else would you confuse that with?

**Comment by SpeedyCraftah** [comment]
It seems that mostly the Rust people are in favour of the fn instead of the C++ people which is the language that's actually supposed to appeal to people.
What I am about to say people will probably dislike as it involves inconsistency and two different specs but: what if we just allow both?

**Comment by BradenWentworth** [comment]
> Consider the keywords `break` or `continue`.

Also considering "package", "import", "for", "while", "match", etc.
I would prefer the full-word consistency of "function" over anything else.

**Comment by jaykrell** [comment]
I don't search for "function" I search for "function foo", vs. "var foo", etc. fn is probably ok.

I agree Rust is the major competitor, safety w/o GC, which Carbon is also aiming for.

I really do think it is for parsers and not just programmers, LL(1) is easier for both.
LALR parsing is unnatural and inefficient.

**Comment by fxshlein** [comment]
I personally always trip over things like  `fn` when reading or describing code, either in my head or using my voice. Having something that is pronounceable _as it is written_ is a huge pro in my opinion.

This doesn't necessarily mean replacing symbols with words; Saying "colon" when I see `:` is not an issue, but there is a certain subset of characters (namely the English alphabet) that should in my opinion only be used in combinations that are pronounceable.

In addition to tripping over it while reading, everyone will probably develop a different way of replacing it in speech or writing (the proposal even discusses this), kind of setting up the community to break the mentioned principle of doing everything "one way", which I think is still good to at least keep in mind when talking about things beyond the scope of the actual language.

**Comment by jaykrell** [comment]
Right, no syllables are saved by “eff en”.
‘Fun’ and ‘func’ are effectively shorter and ‘function’ is same length. Adding vowels is effective in unambiguously removing syllables.

**Comment by ltfschoen** [comment]
> Right, no syllables are saved by “eff en”. ‘Fun’ and ‘func’ are effectively shorter and ‘function’ is same length. Adding vowels is effective in unambiguously removing syllables.

But aren't you assuming most people would use the proper phonetic spelling of the letters "f" and "n", which is "ef en". Aren't most people conditioned to actually pronounce it as the vulgar "eff'n" such that no syllables are saved and audibly when using that default to code by voice it's NSFW?

There may not be a NSFW issue in the military where it's phonetic spelling using [this pronounciation guide](https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/NATO_Phonetic_And_Morse_Code_Alphabet.png/220px-NATO_Phonetic_And_Morse_Code_Alphabet.png) would be "foks trot no vem ber". But unfortunately that has more syllables though and i think most people would prefer the more convenient vulgar pronunciation.

**Comment by KateGregory** [comment]
> Right, no syllables are saved by “eff en”. ‘Fun’ and ‘func’ are effectively shorter and ‘function’ is same length. Adding vowels is effective in unambiguously removing syllables.

I pronounce it (in my head) "fun" and expect most developers also will. Much as I pronounce the C++ std "ptr" suffix as "pointer" the majority of the time, and "std" as "standard" for that matter. The real issue is that we don't know what it will be like to read it, how people will say it to each other when coding together, if it's too short or whatever until there is a body of Carbon code to look through. I'm not seeing new arguments in this thread that were not considered the first time around.

**Comment by Turbine1991** [comment]
> > Right, no syllables are saved by “eff en”. ‘Fun’ and ‘func’ are effectively shorter and ‘function’ is same length. Adding vowels is effective in unambiguously removing syllables.
> 
> I pronounce it (in my head) "fun" and expect most developers also will. Much as I pronounce the C++ std "ptr" suffix as "pointer" the majority of the time, and "std" as "standard" for that matter. The real issue is that we don't know what it will be like to read it, how people will say it to each other when coding together, if it's too short or whatever until there is a body of Carbon code to look through. I'm not seeing new arguments in this thread that were not considered the first time around.

To be honest, if you were to borrow the naming rules of "std" & "ptr" it'd be called "ftn".

Personally "fun" doesn't immediately come to mind for me. JavaScript being the most common language uses the least unambiguous "function". I've used so many languages over 17 years and never come across this keyword or variable naming scheme for referring to a function.

**Comment by chandlerc** [comment]
The leads discussed this, and the considerations here are the same ones we looked at when we originally picked `fn`. For now, we're going to stick with this keyword.
