### ISSUE TITLE
when will developer document be released?

### ISSUE THREAD

**Issue by huaiguoguo** [carbon-language/carbon-lang#1484]
when will developer document be released?

**Comment by jonmeow** [comment]
Carbon is still very experimental: it's not ready for use, and won't be for several years. Since we're so far off from encouraging developer use, developer documentation doesn't make sense at this time.

 Please see https://github.com/carbon-language/carbon-lang#project-status; https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#what-is-carbons-status may also help fill in details for you.

**Comment by huaiguoguo** [comment]
@jonmeow  thank you!
