### ISSUE TITLE
Need a website for documentation

### ISSUE THREAD

**Issue by yadunandanbhat** [carbon-language/carbon-lang#1492]
Can we get a simple readthedocs type of website for the carbon's documentation. Because its hard to navigate in github and the readability is not very good.

Its easy to convert the existing readme to documentation website using tools like mkdocs, kramdown, jekyll etc!

**Comment by emillaine** [comment]
I made a simple script for converting the markdown files under `docs/` to HTML using `pandoc`: https://github.com/emlai/carbon-lang/commit/200eeb3de40303e11aa0a278008eadae71bd031c

You can see the result here: https://emlai.github.io/

It's still missing styles and a navigation bar, but the links seem to be working correctly.

**Comment by Nike682631** [comment]
I'd be happy to work on this issue if it's open for anyone

**Comment by emillaine** [comment]
I updated [my branch](https://github.com/emlai/carbon-lang/tree/website) to use mkdocs after I got it to handle absolute markdown links correctly. It adds a theme, a navbar, and a search, so it looks much better now: https://emlai.github.io/

There's still stuff to do:

- It would be better to show the repository root readme on the front page.
- Create a GitHub action for auto-deploying the site.
- Organize the code snippets in a better way. Currently they're under `Images > Front page snippets for Carbon`.
- Replace the logo with the Carbon logo.
- Customize the theme to make it look less stock and more "Carbony".
- etc.

@Nike682631 If you want to help, we can sync on the Discord!

**Comment by Nike682631** [comment]
@emlai sure, what's your discord?

**Comment by emillaine** [comment]
@Nike682631 emlai#9471

**Comment by yadunandanbhat** [comment]
great work @emlai !!!!

**Comment by seanmrnda** [comment]
We need a book, similar to rust book.

**Comment by joaodematejr** [comment]
recommendation to be studied => https://docusaurus.io/docs

**Comment by seanmrnda** [comment]
Best so far, convertible to pdf.

https://github.com/rust-lang/mdbook

**Comment by jonmeow** [comment]
If you're working on a GitHub pages PR, one thing we've been cautious of is developers interpreting a documentation website as implicit encouragement to use Carbon in production. However, hopefully it's clear to most that Carbon isn't there.

To address that concern, can you maybe add a reminder at the top that Carbon is experimental and not intended for use in applications, linking to https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon

**Comment by emillaine** [comment]
@jonmeow Good idea! I'll make sure to add that.

**Comment by jonmeow** [comment]
I'm moving this to be an issue for leads as they've requested review (a proposal and some details of tradeoffs may be needed, and there's hesitance about whether a website makes sense for Carbon Language at this time). Just to note references: #1526 provides an implementation, and a sample is at https://emlai.github.io/.

**Comment by Tomttth** [comment]
A website would be good for documentation. Also if there is an option for converting to pdf. It would be helpful

**Comment by seanmrnda** [comment]
> A website would be good for documentation. Also if there is an option for converting to pdf. It would be helpful

our best bet is rust-lang/mdbook

> https://github.com/rust-lang/mdBook

**Comment by n-ham** [comment]
@emlai I would be keen to collaborate on replicating your proposed website with my website generator nift.dev. Three dot point sales pitch:

- Has LuaJIT embedded (though if there's a faster md->html converter can use that too);
- Benchmarks way faster than even Hugo (who still brand themselves as world's fastest) plus has had incremental builds since 2015, people should have near instant build times when working on the website rather than having to twiddle their thumbs waiting for builds to finish;
- Is developed in C++ which might be favourable to future Carbon devs who are likely to have C++ backgrounds (one common sentiment among web developers is they prefer to use tools developed in the languages they know like js, c++/carbon devs may be similar);

**Comment by ranbir7** [comment]
can I work on this?
I came here from GsoC organization page........

**Comment by jonmeow** [comment]
> can I work on this? I came here from GsoC organization page........

We use the "leads question" label for things that are awaiting a decision from the project leads about how to proceed. Until they decide that they want a website, and what they want from such, this isn't something that we would proceed on.

(note, it may help to discuss options on #gsoc on [Discord](https://discord.gg/ZjVdShJDAs))

**Comment by AmayX** [comment]
I would like to work on this. I have prior experience in writing documentation.
Please assign me this issue. @jonmeow

**Comment by KateGregory** [comment]
It is possible that a website, easily browsable and indexed by search engines, would help people who are not as comfortable with git and markdown as our current approach. It is definitely a more immersive experience to click around reading things and trying to see what Carbon is and isn't without having to think about the way the information is stored and presented. It would need to be generated from the material in git, so that it could not get out of sync, and we might need a "build step" when any of the source material changes.

We would need to be absolutely clear that this is a website for those helping to build Carbon, not for those wanting to use Carbon, and the the site going live doesn't carry information like "Carbon is open for business!" A top banner as in the provided example https://emlai.github.io/ would work, along with explanations in the places we provide links to this new site.

**Comment by chandlerc** [comment]
Marking this as decided "yes" w/ @KateGregory's [update](https://github.com/carbon-language/carbon-lang/issues/1492#issuecomment-1465269337) for context, rationale, and the criteria.

**Comment by ThePhilosopher4097** [comment]
I would like to work on this...

**Comment by josh11b** [comment]
> I would like to work on this...

@ThePhilosopher4097 , we typically don't assign issues to people, see https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#triage-analyze-or-address-bugs

**Comment by nathany** [comment]
Hi. Just wondering why this issue is closed with "decided yes", as there doesn't appear to be an "official" documentation website? 

Is https://emlai.github.io/ intended to be it? Is it kept up-to-date?

**Comment by jonmeow** [comment]
The leads approved a website in theory, but unfortunately the time spent getting there led to a loss of momentum turning one up. Generally we've just been using https://github.com/carbon-language/carbon-lang/tree/trunk/docs. If you're interested in figuring out the necessary changes, we'd be happy to review a change to help set up GitHub pages.

**Comment by nathany** [comment]
Personally I'm perfectly content to view the documentation on GitHub.
I just came across this from browsing the GitHub Discussions.
