### ISSUE TITLE
New motto: "Safe by default"

### ISSUE THREAD

**Issue by janwilmans** [carbon-language/carbon-lang#1510]
I think we should put "Safe by default" central in Carbon.

**Comment by Clashkid155** [comment]
Isn't that a Rust thing?

**Comment by janwilmans** [comment]
As a new language you should adopt from existing languages what works well, right?

**Comment by chandlerc** [comment]
We already have a goal for safety:
https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/goals.md#practical-safety-and-testing-mechanisms

If this needs to change, that should go through the proposal process.

Personally, I don't think a motto or something as simple as "safe by default" is as effective as the structure we use with our goals. As an example, should memory management be safe-by-default via a garbage collector? For many languages this is a great choice, but it isn't for Carbon because of our goal to support performance critical software which can't afford any of the overhead options for GC. But the motto doesn't help make this tradeoff, or say what to do instead. This is the reason we've tried to structure our goals the way we have with the level of detail and discussion of tradeoffs.

I think the current goals are also pretty aligned with what you're trying to achieve. Is there some gap in that goal that you'd like to see closed?

**Comment by janwilmans** [comment]
What I see missing is the "Practical safety and testing mechanisms" section only talks about unsafe operations. What I like a lot is "Make unsafe or risky aspects of Carbon code explicit and syntactically visible". However, the emphasis I'm missing is that we should also make sure naive code "just works". (but is not necessarily optimally performant)

The reason I think a Motto like this is effective, is because the it's basically a catchy stable reference to the "Practical safety and testing mechanisms" chapter. 

About the separate issues I opened, I considered it more helpful to separate the concerns and discussion about these separate topics.

#1508 (Type safety by default) is a very different topic I think, not sure it would be good to incorporate these topics into one discussion. 

Thanks for the quick feedback
