### ISSUE TITLE
Typo in the README image containing c++ code.

### ISSUE THREAD

**Issue by PiotrekWojtowicz** [carbon-language/carbon-lang#1553]
I think there's a typo in the README image with code comparing carbon to cpp. It's the line with `std::vector<Circle>circles = {{1.0},{2.0}}}` one } is not needed.

**Comment by pacion** [comment]
What is the theme of the IDE? I can fix it.

**Comment by PiotrekWojtowicz** [comment]
No idea.

**Comment by pacion** [comment]
I will try to figure it out.

**Comment by jonmeow** [comment]
Thanks! This is fixed by #1567, and I've noted you as contributor per #1561. Copying #1561 comment though:

Thanks for pointing this out! We use a drive image for the canonical diagram (https://docs.google.com/drawings/d/18OlAdTwIAKlpMYZDyg3V3r244eLv0Es8spnJsrKtPL0/edit). I've fixed that and, since the resulting svg was a bit different here, created #1567 (you can see some of that if you glance at the diff of this PR, versus #1567).

The link to the drive folder is above images in the markdown, but you'd need to request contributor access with an email using DM or similar: for more info, see https://github.com/carbon-language/carbon-lang/blob/trunk/CONTRIBUTING.md#collaboration-systems
