### ISSUE TITLE
I think it will be dead soon

### ISSUE THREAD

**Issue by korkis** [carbon-language/carbon-lang#1560]
A language that declares a type after a function name is always dead.  be careful.

**Comment by TheSimonSays** [comment]
Maybe you're right, but this is not an issue

**Comment by TerryJoo** [comment]
Will TypeScript dead soon too?

**Comment by mragiadakos** [comment]
Hi, I believe your most significant competitors will not be C++ or Rust but Zig and Odin.
Especially Zig will be the hype in the next three months because of colourblind async-await, 'comptime', fast cross compilations and most important, no hidden memory allocations (very useful for NASA!).

Anyways, I hope everything will go smoothly for you. Good luck!

**Comment by mario-neb** [comment]
Hi, you should open a discussion about this topic. as @[TheSimonSays](https://github.com/TheSimonSays) said, this is not an issue

**Comment by korkis** [comment]
I re-posted on Discussion.  I'm looking for a way to delete this post

**Comment by korkis** [comment]
It seems that only admins can delete it. Anyway I will close this.

**Comment by korkis** [comment]
It seems that only admins can delete it. Anyway I will close this.
