### ISSUE TITLE
Shorter standard for the filename extension

### ISSUE THREAD

**Issue by robiot** [carbon-language/carbon-lang#1574]
.carbon is an acceptable filename extension, but I could imagine something shorter like ex. .cb(CarBon) or .cn(CarboN) or .ca(CArbon) or .car(CARbon) to be more ergonomic. If a removal of the .carbon standard filename extension isn't possible, .carbon could be kept + a shorter one like was mentioned before.

**Comment by ngonza27** [comment]
.bon (carBON) could be another extension, but depends more on taste.

**Comment by davidzchen** [comment]
+1 I also think `.carbon` is too long.

There is discussion on the file extension options in the [Code and Name Organization](https://github.com/carbon-language/carbon-lang/tree/trunk/docs/design/code_and_name_organization#different-file-extensions) doc:

> ## Different file extensions
> Currently, we're using .carbon and .impl.carbon. In the future, we may want to change the extension, particularly because Carbon may be renamed.
> 
> There are several other possible extensions / commands that we've considered in coming to the current extension:
> 
> * .carbon: This is an obvious and unsurprising choice, but also quite long for a file extension.
> * .6c: This sounds a little like 'sexy' when read aloud.
> * .c6: This seems a weird incorrect ordering of the atomic number and has a bad, if obscure, Internet slang association.
> * .cb or .cbn: These collide with several acronyms and may not be especially memorable as referring to Carbon.
> * .crb: This has a bad Internet slang association.

The fact that the plan is to have implementation files end in `.impl.carbon` makes the file extension even longer.

I personally really like the `.6c` file extension (which was the original file extension considered for Carbon) since it is not only short and unique but also quite neat given it is based on the isotope syntax of the Carbon element, though the rationale against it is understandable (though I'm sure Elon Musk would think otherwise).

I think Carbon should have a two- or three-letter file extension. If Carbon ends up having separate API and implementation files, I prefer the following convention:

* `.6ca` for API files
* `.6ci` for implementation files

I think the additional letter at the end should mitigate the concern of the file extension sounding like "sexy" when read aloud.

**Comment by robiot** [comment]
Yes, just having .6c could be misinterpreted 🤣. Though I like the .6ca and .6ci that you suggested. But I also like .bon and .car. One downside with them is that they sound kind of weird with an "i" added after, .boni and .cari. One solution would be to put the i before instead which is Steve Jobs approved ;)

**Comment by jonmeow** [comment]
FWIW, I kind of expect the long extension to push us into renaming eventually. This may be a little deliberate. :)

**Comment by emillaine** [comment]
`.cl` could also work, short for **C**arbon **L**anguage.

**Comment by chandlerc** [comment]
FWIW, my personal view is that the length of filename extension doesn't matter much.

I'm quite happy with `.carbon` and `.impl.carbon`.

While I was somewhat interested in a short abbreviation for a commandline tool, I've since stopped thinking that's very important. So I think for now things are fine. My two cents.

Marking this as a question for the leads to get an answer here.

**Comment by robiot** [comment]
@jonmeow 
> FWIW, I kind of expect the long extension to push us into renaming eventually. This may be a little deliberate. :)

I think Carbon is an awesome name with a lot of potential, and rebranding this project at this state would cause some confusion. There are already dozens of blog posts, videos, tweets, and more referencing this project as Carbon. But since it is explicitly stated that it's currently experimental, a name change would be possible, but I wouldn't personally recommend it.

**Comment by davidzchen** [comment]
+1 The fact that the name "Carbon" begins with a C is a nice reference to the C-family of languages and the fact that it is meant to be a C++ successor. In addition, the element Carbon is the backbone of all organic molecules and polymers that make up all life on earth and the technology around us. I think Carbon is a wonderful name.

@jonmeow out of curiosity, are there any alternative names for Carbon that are being floated?

By the way, in #1590, '.carb' is used in the reporter's error message snippet. Perhaps this can be another option?

Also, would it be possible to not have separate API and implementation files altogether, following the approach of other modern languages such as Swift, Rust, Go, etc.?

**Comment by robiot** [comment]
I totally agree with your reasoning about Carbon as a name.

.carb seems nice. Tho it might clash with https://whatext.com/carb


I like the idea of not having an implementation file, since in my experience, having both header files and implementation files have not contributed with making code(bases) clean.
Tho since this is a successor to c++, many developers might consider implementation files + header files since that is what they are used to. But imo, having it all in one file makes the whole developer experience much more ergonomic.

**Comment by anton-roos** [comment]
I think `.carbon` is unambiguous, I understand that it is long but I don't like the alternatives `.cn` `.ca` `.car` `.bon`.

`.ca` - Initial Telnet Cache
`.cn` - CNwin/MLwin account data
`.car` - This is ambiguous and can mean a lot of things. A few programs use this already.
`.bon` - This is a Binary Object Notation Document
`cl` - I like the suggestion `.cl` for **C**arbon **L**anguage, there are Cursor Libraries that use `.cl`

> .cb or .cbn: These collide with several acronyms and may not be especially memorable as referring to Carbon.

`.cb` - "This cb file type entry was marked as obsolete and no longer supported file format." I like .cb because it ties in with cpp, and cs. Unfortunately Carbon is one word so the "b" just doesn't add the same as "pp" to cpp and "s" to cs.

 I still think `.carbon` is better option at this point. What do you guys think about `.cb`?

**Comment by robiot** [comment]
Since the B in the word Carbon stands out a bit on pronunciation, I think .cb is a nice extension.

A majority of people that voted in this poll https://github.com/carbon-language/carbon-lang/discussions/1597 also preferred the .cb extension.

**Comment by knucklepunch** [comment]
.6ca is perfect. What about .c12 extension?

**Comment by rafaelsierra** [comment]
I would refrain from using `ca` because Ca is calcium and `cl` because Cl is chlorine

`c6` might be good because carbon fiber is made out of hexagonal carbon structures (or a benzine ring if we ignore the hydrogen)

**Comment by chandlerc** [comment]
The leads discussed this and while we're somewhat sympathetic to the desire for a short extension, it isn't a change we want to make right now. We'll stick with `.carbon` for now.

**Comment by devrimcavusoglu** [comment]
> .c6: This seems a weird incorrect ordering of the atomic number

@davidzchen Isn't this the correct ordering for chemical formula ? Afaik, atomic numbers rather succeed the element symbol than preceeding them.

So `c6` is carbon, I don't know what `6c` is.
