### ISSUE TITLE
Using '..' to access pointers.

### ISSUE THREAD

**Issue by EdSaleh** [carbon-language/carbon-lang#1583]
Hello,

I think the syntax `..` to access pointers could be a good and cleaner addition to the language.

Currently: `pointer->value` is used, I propose to use `pointer..value`. The language can support both syntax.

Thank you,

**Comment by emillaine** [comment]
IMO just `pointer.value` would be better, since [pointers are non-null](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/README.md#pointer-types) anyway. Related: https://github.com/carbon-language/carbon-lang/discussions/1545

**Comment by BradenWentworth** [comment]
If there are no null pointers, and you can't do pointer arithmetic, then what is the point of them, wouldn't everything just be direct references to either an existing value (or an Option<>)?

**Comment by davidzchen** [comment]
One potential issue for using '..' as a pointer access operator is that '..' is used as the range operator in a number of other ranges, for example in [Ruby](https://stackoverflow.com/questions/24796819/difference-between-3-dot-range-operator-and-2-dot-range-operator-in-flip-flop-ru)

**Comment by EdSaleh** [comment]
Hello,

Thanks for the discussion.

Both using '.' and '..' to access pointer are good improvements than the current '->'. The problem with '.' is that the language tries to be as close as possible to C++ and treating object pointers as just object references similar to C# and Java would be different than C++.

Regarding the range operator, if range operator would ever be supported, the usage case and surrounding syntax and grammer and context is completely different when '..' is used for range or pointer access, similar to '->' is used in the language for return type and accessing pointers.

Thank you,

**Comment by OlaFosheimGrostad** [comment]
> Both using '.' and '..' to access pointer are good improvements than the current '->'. The problem with '.' is that the language tries to be as close as possible to C++

The main issue with '.' is that it does not work with smart pointers. '..' seems like a fair tradeoff.

I believe Dart introduced '..' for reusing the object reference, like this: 'obj.set_x(1)..set_y(2);' is the same as 'obj.set_x(1); obj.set_y(2);' or something like that.

**Comment by jwtowner** [comment]
> The main issue with '.' is that it does not work with smart pointers. '..' seems like a fair tradeoff.

Or we could invert what is meant by '..' to bind to methods defined only in the outer type, circumventing any `operator.` override.

**Comment by OlaFosheimGrostad** [comment]
> Or we could invert what is meant by '..' to bind to methods defined only in the outer type, circumventing any `operator.` override.

Do you mean that 'expression..name' would try:

1. expression->name
2. (*expression).name
3. expression.name

in order? That is an interesting idea! (but that will mean less strong typing)  Two other options:

1. give dereference high priority so that '*pointer.value' is the same as '(*pointer).value'
2. auto-dereference all pointers so that you use '&' as an un-dereferencing operator. So C++ 'pointer = &object' has to be written '&pointer = &object' and C++ '(*pointer).value' simply becomes 'pointer.value'.

But, pointers in generic programming are a bit problematic, is the pointer a value or is it containing a value? Both? Regardless, whatever is done for accessing fields should be consistent with assignment. Simula had ":-" for pointer assignment and ":=" for value assignment, but that does not work well for containers of pointers where you want to treat pointers as values... There are no perfect design options :-/, so you end up with figuring out what the least imperfect option is (for what you think is the dominating use case).
