### ISSUE TITLE
Multidimensional arrays and slices

### ISSUE THREAD

**Issue by foxtran** [carbon-language/carbon-lang#1661]
C++ lacks support of multidimensional arrays and usually theirs support comes from 3-rd party libraries like [BOOST](https://www.boost.org/doc/libs/1_79_0/libs/multi_array/doc/user.html).

I found example of nested arrays: https://github.com/carbon-language/carbon-lang/blob/trunk/explorer/testdata/array/nested.carbon.

There is the definition of nested array:
```cpp
  var x: [[i32; 3]; 2] = ((0, 1, 2), (3, 4, 5));
```

## definition
I would like to have continuous in memory multidimensional array:
```cpp
  var x: [i32; 3; 2] = ((0, 1, 2), (3, 4, 5));
```

For avoiding explicit difinition of array sizes, use `:`:
```cpp
   var ArrayOfArrays: [[i32, :]; :] = ((0, 1, 2), (3, 4, 5));
   var MultiDimArray: [i32, : ; : ] = ((0, 1, 2), (3, 4, 5));
```

## functions
For reshaping arrays, I need function `reshape`:
```cpp
  var x: [i32; 3; 2] = reshape(/*array=*/(0, 1, 2, 3, 4, 5), /*shape=*/(3, 2));
```
For getting shape array, `shape` function is:
```cpp
  var s: [i32; 2] = shape(x); // s = (3, 2)
```
function `size` returns total array size:
```cpp
  var l: i32 = size(x); // l = 6
```

## operations
Arrays can be easily modufied by any operators.
Vector-way:
```cpp
  var x: [i32; 3; 2] = ((0, 1, 2), (3, 4, 5));
  x *= 2; // x = ((0, 2, 4), (6, 8, 10));
```
Scalar-way:
```cpp
  var x: [i32; 3; 2] = ((0, 1, 2), (3, 4, 5));
  var y: auto = -x;
  // each to each elements are summarized
  var z: auto = x + y; // z = ((0,0,0), (0,0,0))
```
For scalar-way, if shape are inconsistent, RUNTIME error is.

## slices

Slices, presented at https://raw.githubusercontent.com/carbon-language/carbon-lang/trunk/docs/images/quicksort_snippet.svg, are quite good.

Here, I would add small extension of slices. Not only `a:b` (with omitted a, b or both of them) can be used as slice generator, but also array:
```cpp
   var ind: [i32; :] = (0, 1, 1, 2, 2);
   var x: [i32; :] = (3, 5, 7);
   var y: auto = x[ind]; // y = (3, 5, 5, 7, 7)
```

## automatically allocated arrays

While in difition section, two examples were:
```cpp
   var ArrayOfArrays: [[i32, :]; :] = ((0, 1, 2), (3, 4, 5));
   var MultiDimArray: [i32, : ; : ] = ((0, 1, 2), (3, 4, 5));
```

Here, I want to introduce automatically allocated arrays where sizes are not known at definitions:
```cpp
   var ArrayOfArrays: [[i32, :]; :];
   var MultiDimArray: [i32, : ; : ];
```
Such arrays must be explicitly defined via assignment of memory allocation.

### Assignment:
```cpp
  var y: [i32; :, :];
  var x: [i32; 3; 2] = ((0, 1, 2), (3, 4, 5));
  y = -x;
```

### Memory allocation:
```cpp
  var x: [i32; :, :];
  allocate(x, /*shape=*/(3, 2));
```

Deallocation can be done via:
```cpp
   deallocate(x);
```
Firstly, all destructors of `x` will be called then memory will be freed.

**Comment by jloveric** [comment]
Seems like this stuff should be critical given the importance of numerical methods and machine intelligence.

**Comment by w-m** [comment]
Because of the demand in data science and machine learning, multidimensional arrays have seen an incredible amount of attention in the last years in Python, via various libraries/frameworks. Perhaps Carbon could benefit from all this work, by taking design inspiration from the Python community. There are quite a few competing implementations, but a [consortium](https://data-apis.org/blog/announcing_the_consortium/) of different library maintainers has recently worked out a Python Array API Standard. From their [purpose and scope](https://data-apis.org/array-api/latest/purpose_and_scope.html) document:

> Python users have a wealth of choice for libraries and frameworks for numerical computing, data science, machine learning, and deep learning. New frameworks pushing forward the state of the art in these fields are appearing every year. One unintended consequence of all this activity and creativity has been fragmentation in multidimensional array (a.k.a. tensor) libraries - which are the fundamental data structure for these fields. Choices include NumPy, Tensorflow, PyTorch, Dask, JAX, CuPy, MXNet, Xarray, and others.
> 
> The APIs of each of these libraries are largely similar, but with enough differences that it’s quite difficult to write code that works with multiple (or all) of these libraries. This array API standard aims to address that issue, by specifying an API for the most common ways arrays are constructed and used.

Borrowing the main ideas from this mature API might save Carbon years of having to go through the same story, and reinventing the wheel several times. Of course Carbon and Python are very different languages, so I'm aware that the whole API might not be a perfect fit. Also having a whole array library (with linalg, statistics and such) is perhaps not what the "batteries-included" tagline in the Carbon README refers to..

But designing the multidimensional array language features in Carbon in a way that allows for an array library to get as close to the Python Array API as possible would be very beneficial for users who live in both worlds.

Here are some links directly into the API spec:
Array object: https://data-apis.org/array-api/latest/API_specification/array_object.html
Indexing: https://data-apis.org/array-api/latest/API_specification/indexing.html

**Comment by timofeymukha** [comment]
Coming from the community of computer simulations, I strongly support making a multidimensional array a first-class citizen in the language. This is one feature that makes modern Fortran more attractive than C++ when it comes to a choice of compiled language. Having Carbon implement this right from the inception would give it a major boost in the eyes of the scientific community. Of course, machine learning applications, which are mentioned above are also very relevant.

**Comment by Asaaj** [comment]
This topic is finally gaining traction in C++, so it's worth considering their design and potential interoperability, as we see with C++ `std::span` and Carbon `Slice`. [`mdspan`](https://github.com/cplusplus/papers/issues/96) was approved for C++23, and [`mdarray`](https://github.com/cplusplus/papers/issues/461) is looking like it'll be in C++26.

**Comment by chandlerc** [comment]
I believe the current work *is* considering multidimenisonal arrays -- @geoffromer can comment more.

But there isn't anything decided here yet, so I don't think there is much to do with this issue though. When the array designs start moving with proposals, if they don't provide the multi-dimensional support, I would comment there?

Closing for now as "not-planned" which is a bit of a misfit because it *is* planned, but specifically not done or with anything to really track in an issue. That said, we can always re-open if needed here.

**Comment by emillaine** [comment]
There's some related discussion about multidimensional arrays in the array type syntax proposal #1787, starting from [here](https://github.com/carbon-language/carbon-lang/pull/1787#discussion_r931712143).

**Comment by mlaugharn** [comment]
I think something that would also be really powerful is built-in tensors with optimal rearrangement / reduction, see e.g. einops, torchdim, TACO tensor compiler, opt-einsum. 

https://github.com/arogozhnikov/einops

https://github.com/facebookresearch/torchdim

http://tensor-compiler.org/

https://optimized-einsum.readthedocs.io/en/stable/

Having that at the language spec level would be immensely powerful, imo.

**Comment by msadeqhe** [comment]
Nice idea. IMO the syntax could be improved a little if we use `,` instead of `;` to separate each dimension's length:

```carbon
var x: [i32; 2, 3] = ((0, 1, 2), (3, 4, 5));
```

**EDIT:** Maybe it's more natural to put outer dimensions before inner dimensions.

**EDIT:** So the way we declare arrays will be similar to the way we get elements from them:
- `x` type is `[i32; 2, 3]`. Comma is between dimensions' lengths.
- `x[1, 2]` is `5`. Comma is between dimensions' indexes.

Also we may use `_` instead of `:` for deducing each dimension's length:

```carbon
var y: [i32; _, _] = ((0, 1, 2), (3, 4, 5));
```

In general:

```carbon
[TYPE; D1, D2, ...]
```

And `[TYPE]` can be equal to `[TYPE; _]` (the same as `[TYPE;]`).
