### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by robiot** [carbon-language/carbon-lang#1689]
[removed by jonmeow: please don't post logo suggestions right now]

**Comment by c-v-meyer** [comment]
It looks very nice, no doubt, but it indeed has many similarities with the logos of the "C-Languages" (C, C++, C#, HolyC) due to the hexagon shaped background and the style of the "C".

My suggestion: Keep the black background and the overall style, but change the background to a rectangle (like an element of the periodic table).

**Comment by nadiasvertex** [comment]
I think "overloaded functions cannot differ only in return type" is analogous to "programming language icons cannot differ only in color".

What about using interlocking hexagons to show that it integrates tightly with C++?

**Comment by jonmeow** [comment]
Sorry, but I'm closing and locking this thread. We don't have a logo right now because they're a tricky area. I'm removing logo suggestions.
