### ISSUE TITLE
Question: why not just contribute to zig

### ISSUE THREAD

**Issue by waozixyz** [carbon-language/carbon-lang#1710]
i don't see why we need to create new languages all the time instead of just improving on existing languages like zig that already have interoperability with c and c++

**Comment by MichaelBonnet** [comment]
The design goals are different. Additionally, this is not an "issue" in the sense of the intended use of the feature, and should be closed.

**Comment by junlarsen** [comment]
The goals for Carbon are a bit different than Zig's. Carbon wants to find a migration path from C++ code into a more modern language that tries to solve a lot of the existing problems with C++.

Additionally, this should probably be turned into a discussion if there is interest in dicussing this further

**Comment by jonmeow** [comment]
If Zig works for you, please use it!

However, Zig's language design differs from Carbon in meaningful way. For example, we think Carbon has a different story for migration of C++ codebases and developers that is really fundamental. I'd expect we're going to continue heading down a different path from Zig.

Note, I'm not turning this into a discussion because we don't want our forums to be used for language debates.
