### ISSUE TITLE
Pointer an memory management

### ISSUE THREAD

**Issue by martcpp** [carbon-language/carbon-lang#1755]
Let use a little bit of self memory management as that of c++ to make the language flexible to new learner

**Comment by WarEagle451** [comment]
A big reason to use system languages like C++ or hopefully Carbon is that there is no garbage collector. In fact C++20 or C++23 just removed it from the spec because everyone refused to implement it.

**Comment by martcpp** [comment]
The project should consider the fact that New user don't want to go through memory management stress if so looking through how to still make carbon fast but with little addition of some stress free features will be plus

**Comment by WarEagle451** [comment]
If a garbage collector was added I wouldn't even touch this language, I'd probably use Java or Python. The goal isn't to be friendly to new comers but to be a successor to C++. One of the main reasons people choose C++ is because memory has to be managed manually, if that wasn't the case for Carbon it would not be a successor. Also RAII (Which I actually couldn't find in the Carbon docs but I'd be shocked if it wasn't in the language) covers most use cases as long as pointers aren't involved.

**Comment by OlaFosheimGrostad** [comment]
> If a garbage collector was added I wouldn't even touch this language, I'd probably use Java or Python. The goal isn't to be friendly to new comers but to be a successor to C++.

Yes, I agree. Although, they should make shared_ptr easy to use and could implement syntax sugar for it as well as ARC optimizations. shared_ptr could be used in code paths that do not require high performance.

**Comment by OlaFosheimGrostad** [comment]
> > If a garbage collector was added I wouldn't even touch this language, I'd probably use Java or Python. The goal isn't to be friendly to new comers but to be a successor to C++.
> 
> Yes, I agree. Although, they should make shared_ptr easy to use and could implement syntax sugar for it as well as ARC optimizations. shared_ptr could be used in code paths that do not require high performance.

**Comment by jonmeow** [comment]
The initial issue is vague, but I'm going to assume that this is is mostly about memory management as with GC (e.g., Java or Python), reference counting (e.g., Swift), or possibly "managed code" (e.g., C#). If you can use one of these languages, you should! However, Carbon is targeting a different audience.

This issue seems to be addressed best by our [safety strategy](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/safety_strategy.md). I think the alternatives considered in the safety strategy explain our choices here. While we may add other forms of safety in the future, I think it needs to be expected that C++'s memory models will be followed in many ways, due to the fundamental impacts on performance and C++ interoperability (both of which are [key design goals](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/goals.md#language-goals-and-priorities)).

**Comment by nmsobri** [comment]
> > If a garbage collector was added I wouldn't even touch this language, I'd probably use Java or Python. The goal isn't to be friendly to new comers but to be a successor to C++.
> 
> Yes, I agree. Although, they should make shared_ptr easy to use and could implement syntax sugar for it as well as ARC optimizations. shared_ptr could be used in code paths that do not require high performance.

Imho, using `defer` to manage memory like in zig is the best way to go..

**Comment by h3har** [comment]
@nmsobri That's quite low level. If I understand Zig's `defer` mechanism properly (I don't use Zig), it means you would have to manually free/destruct everything yourself - obviously the `defer` and `errdefer` makes it much more pleasant than in C, but it's still manual. Given the goals of Carbon I'd have thought emulating C++ and Rust's RAII and destructor behaviour would make more sense.

**Comment by nmsobri** [comment]
> @nmsobri That's quite low level. If I understand Zig's `defer` mechanism properly (I don't use Zig), it means you would have to manually free/destruct everything yourself - obviously the `defer` and `errdefer` makes it much more pleasant than in C, but it's still manual. Given the goals of Carbon I'd have thought emulating C++ and Rust's RAII and destructor behaviour would make more sense.

correct, it still manual free.. but surely its one step up from C.. when u `malloc` or `calloc`, the next line u straight `defer` the memory clean up.. im not familiar enough with C++ RAII, but last time i used C++, i was so frustrated with so many smart pointer that made me stop using C++ completely.. but i can see RAII will made everything much more simple.. but i strongly opposed against Rust borrow checker system, it make code quite confusing, at least for me

**Comment by WarEagle451** [comment]
> but i strongly opposed against Rust borrow checker system, it make code quite confusing, at least for me

100% agreed. That is one of the main reasons I don't use Rust. Hopefully that does not get added to Carbon

**Comment by chandlerc** [comment]
FWIW, there doesn't seem to be a specific issue here.

As @jonmeow described above, GC and reference counting don't align with Carbon's goals, and we have a safety strategy that outlines the consequences and what we plan to do to work on it. Closing this for now.
