### ISSUE TITLE
Support l10n docs as early as possible

### ISSUE THREAD

**Issue by awxiaoxian2020** [carbon-language/carbon-lang#1785]
I know it just an experimental language now. But good l10n docs can make more people join us. I can make PRs for zh-CN. Are there any plans?

**Comment by C-BJ** [comment]
I can also help with this

**Comment by geoffromer** [comment]
We are probably still [several years away](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon) from wanting to provide end-user documentation in any language (even English). The current documentation is targeted at contributors (and potential contributors) to the design and implementation of the language. It would be great if we could enable non-English-speakers to contribute effectively to the project, but I don't really see how to get there, and translating the existing docs seems like a pretty small piece of the problem.

**Comment by awxiaoxian2020** [comment]
> We are probably still [several years away](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon) from wanting to provide end-user documentation in any language (even English). The current documentation is targeted at contributors (and potential contributors) to the design and implementation of the language. It would be great if we could enable non-English-speakers to contribute effectively to the project, but I don't really see how to get there, and translating the existing docs seems like a pretty small piece of the problem.

Doc Translations is a small event or problem indeed. But it's no doubt that translations will contribute to the eco-system. As an experimental language, I think the original docs for contributors are still valuable in the future as "a history material". And if we start translations earlier, we will build a good relationship or workflow for this. It's useful for the end-user docs.

**Comment by C-BJ** [comment]
> We are probably still [several years away](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon) from wanting to provide end-user documentation in any language (even English). The current documentation is targeted at contributors (and potential contributors) to the design and implementation of the language. It would be great if we could enable non-English-speakers to contribute effectively to the project, but I don't really see how to get there, and translating the existing docs seems like a pretty small piece of the problem.

Are you worried about the tracking of translated content? https://weblate.org/ may solve this problem

**Comment by geoffromer** [comment]
> Are you worried about the tracking of translated content? https://weblate.org/ may solve this problem

No, I'm thinking about things like, how would a non-English-speaker be able to review design proposals, author their own proposals, or participate in review of their proposals? How would they participate in Discord or other discussion forums?

**Comment by chandlerc** [comment]
> > Are you worried about the tracking of translated content? [weblate.org](https://weblate.org/) may solve this problem
> 
> No, I'm thinking about things like, how would a non-English-speaker be able to review design proposals, author their own proposals, or participate in review of their proposals? How would they participate in Discord or other discussion forums?

I'd be happy to create specific channels in Discord that focus on non-English discussions FWIW to allow folks to collaborate and discuss in those languages. Mostly we'd need to have some folks actively contributing to the project who could help moderate them.

However, I definitely share the concern that we will need to pick a single language in which to collaborate and code review the initial proposal or doc changes. That is in no way "good" or "ideal", but I also don't know how to avoid it or create a meaningful alternative.

At the moment, because our primary audience is *specifically* those collaborating directly on the development of these documents, it isn't clear that something like weblate.org would add much value. But we should definitely explore that as soon as the design starts getting even close to complete and we're trying to get broader evaluation of the design from potential users?

That at least is my best idea of how to proceed in the short term, despite the fact that it is clearly imperfect. =[

**Comment by awxiaoxian2020** [comment]
Thank you all indeed. I understand the idea is not suitable for now. close as not planned.
