### ISSUE TITLE
Is the Carbon Explorer where all the technical examples are found?

### ISSUE THREAD

**Issue by CodeKitty-max** [carbon-language/carbon-lang#1794]
If this is the case, then would it be appropriate to contribute to use cases that combine multiple concepts just for example purposes?
For example, I want to try to build a neural net in carbon. Would it be a good fit for the Carbon explorer?

**Comment by jonmeow** [comment]
Please don't build anything in Carbon right now: see https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-soon-can-we-use-carbon

Also, please use GitHub Discussions or Discord to ask questions. Issues are appropriate for things like bugs, features, and other things that can be fixed with a PR.

**Comment by jonmeow** [comment]
That is, explorer *is* where examples are, but I don't think a neutral net is going to be something that should be built any time soon.
