### ISSUE TITLE
Array constructor is the same as typle constructor

### ISSUE THREAD

**Issue by foxtran** [carbon-language/carbon-lang#1838]
Array definition:
https://github.com/carbon-language/carbon-lang/blob/2fa74f1d71e9ffda42f3459917ed265439c2bd6f/explorer/testdata/array/index.carbon#L15
Tuple constructor:
https://github.com/carbon-language/carbon-lang/blob/2fa74f1d71e9ffda42f3459917ed265439c2bd6f/explorer/testdata/generic_function/swap.carbon#L15

I'm a bit confused with these definitions... What is about usage of traditional square brackets in array constructors?

**Comment by geoffromer** [comment]
`(0, 1)` and `(tuple[1], tuple[0])` are both tuple literals. The tentative design here is that an array can be initialized from a tuple if the tuple has the right number of elements, and they can all be converted to the array's element type. At the moment there is no array literal syntax in Carbon, although we could add one if it turns out to be needed.
