### ISSUE TITLE
Why the filenames in explorer use snake_case.carbon and not UpperCamelCase.carbon?

### ISSUE THREAD

**Issue by sirlordt** [carbon-language/carbon-lang#1857]
I noticied all files of explorer use snake_case.carbon and not UpperCamelCase.carbon. The language use UpperCamelCase for type names, method , functions and maybe var names?. additional use snake_case only to language keywords. 

But why? Any specification or design goal i missing?

I think is more consistent use UpperCamelCase.carbon for the file names.

**Comment by libbooze** [comment]
I presume it is inspired by google c++ style guide. And I actually like it.

https://google.github.io/styleguide/cppguide.html#File_Names

**Comment by malkia** [comment]
Just guessing, but filenames under Windows and OSX are case-insensitive (but preserving), so UpperCamelCase is same as upperCamelCase which might be unfortunate if the verbatim filename is used somewhere else, and then it won't match. (or leave two or more files on linux/unix systems).

**Comment by davidzchen** [comment]
Yes, it is based on the Google C++ style's file name convention. I prefer 'lowercase_snake_case' to keep it consistent with the C++ style guide. 

And plus, Rust and Go also have UppercaseCamelCase for types, and Go also uses this for function names, but both languages have fully lowercase file names.

**Comment by jonmeow** [comment]
To give an official answer, for C++ in particular, we [use Google C++ style](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/cpp_style_guide.md), including file naming convention. We tend to use this style for other filenames because most code is C++, and there's a benefit to consistency in names.

I don't think we've really discussed what filenames to use for Carbon, as Carbon code is only being written in unit tests, so I don't know whether that'll change in the future. 

I'm going to shift this to a leads question in case they want to weigh in on whether it's worth a different filename approach for Carbon (which could for example be adopting UpperCamelCase to match package/class names -- as @malkia correctly points out, there are cross-platform issues with creating filename casing dependencies, but casing preservation is likely sufficient).

**Comment by sirlordt** [comment]
Ok great!. 

Thanks to all for your feedback.
