### ISSUE TITLE
Add a "Why not D?" FAQ entry

### ISSUE THREAD

**Issue by lexi-nadia** [carbon-language/carbon-lang#1875]
See https://github.com/carbon-language/carbon-lang/discussions/1448.

**Comment by OlaFosheimGrostad** [comment]
I don't think you need to justify creating a new language. Carbon is already distinct enough from other languages and has gotten many things right that others refuse to address…

(I think people are asking "why not language X" because they feel Google is a threat to their own ecosystem, perhaps rightfully so.)

**Comment by KateGregory** [comment]
FAQ entries are not written because we need to justify or explain things to get permission to do what we're doing. They are written because the same questions keep being asked, and it's repetitive to write a fresh answer each time. Lots of people asked "why not just use Rust?" and "why not try improving C++?" so FAQ entries give them the answer they need while saving time for those who are being asked. If people are asking "Why not D?" then we add an entry for it. Not because it's a question whose answer establishes our legitimacy; just because people ask.

**Comment by OlaFosheimGrostad** [comment]
Ok, but you cannot really answer the underlying question which is: "Will we be able to retain the game and embedded devs etc or will they move to Carbon?".

You can only answer the surface question, which they probably already know the answer to, as D is very different from Carbon (the claims in #1448 are not accurate, D is now focusing heavily on C interop without bindings and D has no plans to cover C++ interop for templates that haven't been instantiated in C++ code).

**Comment by chandlerc** [comment]
(I am actually working on this)

**Comment by jonmeow** [comment]
I think Carbon's just exploring different trade-offs than D, for example around GC. We'll add something to the FAQ it this question comes up frequently, but it's not something we've been seeing come up for a while.
