### ISSUE TITLE
Semicolon

### ISSUE THREAD

**Issue by jloveric** [carbon-language/carbon-lang#1924]
Is the semicolon actually required? It is no longer required in javascript so it seems like you could get rid of it here.

**Comment by jonmeow** [comment]
I'm going to let the leads respond here.

For convenience I'll copy @josh11b's https://github.com/carbon-language/carbon-lang/discussions/1739#discussioncomment-3255201:

> My recollection of the reasoning behind required semicolons is:
> 
> * matches C/C++
> * makes it easier for tools to parse and operate on source code
> * readability is more important to us than writability
> 
> That being said, we do want it to be as easy as possible to determine if a `;` is missing for error detection and recovery and so things like IDEs can help put them into the code for you. That mostly impacts the rest of the grammar, though.
> 
> Incidentally, automatic semicolons are a stronger restriction on the rest of the grammar.
> 
> I would also like to note that the rules for automatic semicolon insertion end up complicated, and very different for different languages. We have a strong preference for simple rules, particularly at first. If something is shown to be a real problem in practice, we can always add complexity later.
> 
> Comments saying "I like X" or "I don't like X" don't really contribute to the conversation. Much more helpful would be a reason for or against X that hasn't already been considered.

**Comment by geoffromer** [comment]
It's important to distinguish between two possible features here:

- Some languages (such as Python, the C preprocessor, the BASIC family, and many others) treat a line break as ending a statement, usually with exceptions for things like lines ending in `\` or lines with unclosed delimiters. In such languages, semicolons are never necessary, unless for some reason you need to pack multiple statements onto a line.
- In JavaScript, every statement ends with a semicolon, but if (and _only_ if) there's a syntax error in the code you wrote, JavaScript will attempt to recover by inserting semicolons at the end of lines. This means that if two adjacent statements would also be valid as a single statement, you _must_ add a semicolon between them. It also means that you can't tell whether a line of code is a complete statement just by looking at that line, because it could depend on the contents of the following lines.

I tend to think the first approach isn't right for Carbon, but it's basically sound. On the other hand, the JavaScript approach is widely regarded as a mistake (even the original designer [agrees](https://brendaneich.com/2012/04/the-infernal-semicolon/)), so Carbon definitely should not follow that example.

**Comment by chandlerc** [comment]
The leads chatted and agree with the [rationale write up](https://github.com/carbon-language/carbon-lang/discussions/1739#discussioncomment-3255201) by @josh11b that was quoted here. Marking this as decided "not planned".

**Comment by jonmeow** [comment]
@chandlerc Should the decision to include semicolons be codified by a proposal?

**Comment by chandlerc** [comment]
> @chandlerc Should the decision to include semicolons be codified by a proposal?

If it isn't already covered by a proposal around statements, yes, it should. (I thought it might have already been covered, but haven't checked thoroughly...)

**Comment by jonmeow** [comment]
I may be wrong here, but I don't think we've had one -- https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/blocks_and_statements.md has no references.

**Comment by jonmeow** [comment]
Filed #2002 to track the proposal need.
