### ISSUE TITLE
Welcoming? Successor language?

### ISSUE THREAD

**Issue by jmafc** [carbon-language/carbon-lang#1948]
Some mostly random thoughts (after watching the announcement video, including Q&A, and browsing some issues):

Perhaps the community is welcoming, but have you considered that the syntax, albeit easier to parse, may not be welcoming to the thousands of C/C++ developers who are used to `type` `name` and would see `let (or var) name: type` as a retrogression to Pascal or BASIC? Even if you provide a tool to convert existing code, the new code will *have* to be written using the new syntax, so arguably that's an unwelcome change.

I'm afraid that claiming Carbon is a kind of "successor" language is stretching the analogies a bit. C++ of course kept 99% of the C syntax. If I'm not mistaken, Typescript did not introduce a radical new syntax for declaring entities, only type annotations. I'm not familiar with Kotlin, but it doesn't appear that different from Java.

The example in the README uses C++ #include's rather than the more modern module syntax. That is somewhat similar to the way initial Rust presentations would emphasize how "atrociously" C++ behaved with examples using raw pointers instead of unique or shared pointers (I realize most existing C++ code uses #include's, but it seems fairer to do a comparison using the newer syntax).

Last but certainly not least is the issue of error handling. I could not find a clear position but it seems that Carbon may *not* have `try`/`catch`. If so, is that seen as an improvement? How can Carbon then be a "successor" to C++?

**Comment by jmafc** [comment]
Forgot to mention that there is already a "successor" language to C++ that, IIRC, has kept most of the C/C++ syntax intact (except for arrays). It's Walter Bright's D. It has modules and even design by contract features.

**Comment by cabmeurer** [comment]
I can understand your thoughts on this, and would like to share some of mine. The details of chosen syntax you described as retrogression, I feel like is actually much more common for modern languages/design. With that in mind, I think the "thousands of C/C++ developers" that are use to `type name` are bound to be familiar enough with other languages like Kotlin, Go, Swift and many other languages that use the `let (or var) name: type` syntax.
I personally feel the mission for Carbon is to be a successor to C++, however whether or not you agree with that is a different thing. I have had several conversations with different devs, and some of their opinions are that rather than create a new language, that the efforts should be made to make another language the 'successor' (I've heard people say this about Rust, Go and even Swift) as of now, the language is experimental and time will tell.
As far as error handling, if we take a look at the docs, [Roadmap](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/roadmap.md) it is stated that version 0.1 isn't slated to be released until the end of this year, and 1.0 isn't planned until 2024/2025. To quote the Roadmap: 
"The design choices made to reach this point are expected to be experimental, and many of them may need revisiting before we reach 1.0, but the broad shape of the language should be clear at this point, and it should be possible to write non-trivial Carbon programs." So I would imagine something like `try`/`catch` would be reasonable to expect in the future.

**Comment by jmafc** [comment]
It's one thing to know about `let/var name: type`-style syntax, it's quite another to be agreeable to code in it day in and day out. Rust, Go and Pascal's declaration syntax may be "modern", but I wouldn't want to use it on a daily basis.
"Successor" in what sense? C++ is a successor to C because you can take a large software base written in C, rename the `.c`s to `.cpp`s (or whatever is your preferred C++ extension) and 99% of the files will compile (and you may get better warnings). I haven't actively looked at D recently but with what they called `-BetterC` you could compile a C file directly. Carbon at this moment is vaporware. At least Go, when it was announced outside of Google, had an implementation (perhaps written in C++, but nevertheless something "tangible") and although they didn't have generics and their build system went through multiple iterations after their first release, the overall syntax and language semantics were about 80% settled.
Plus one needs to consider that C++ will *not* remain static until 2024/2025 (that's why any comparisons ought to be against C++20 with modules and even what's been announced for C++23).
I'm sorry but your quote from the Roadmap doesn't inspire confidence.

**Comment by davidhunter22** [comment]
In my personal opinion Carbon should drop any talk of "Successor to C++". As a long time C++ prgrammer I would love a better C++ but it seems very arrogant to claim to be that from the start, to the point where I am put of even trying the language. I would much prefer a more humble approach, for instance just focus on why if your a developer/company doing C++ why Carbon may be better than continuing to use C++ or switching to D or Rust and why migrating to it is easy.

Also I would stress the Visual Studio integration. The entire effort will always be a niche, like D, without this.

**Comment by cjdb** [comment]
Thanks for your input! This is more of a discussion than an issue, so I'm going to close this. Please see [Where should I ask questions about Carbon Language?](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#where-should-i-ask-questions-about-carbon-language) from our FAQ.

I will address some points very briefly, but please use the appropriate channels instead of responding here.

> Perhaps the community is welcoming, but have you considered that the syntax, albeit easier to parse, may not be welcoming to the thousands of C/C++ developers who are used to type name and would see let (or var) name: type as a retrogression to Pascal or BASIC? Even if you provide a tool to convert existing code, the new code will have to be written using the new syntax, so arguably that's an unwelcome change.

The Carbon Language declaration syntax is to counter C++'s [most vexing parse issue](https://en.wikipedia.org/wiki/Most_vexing_parse). 

> I'm afraid that claiming Carbon is a kind of "successor" language is stretching the analogies a bit. C++ of course kept 99% of the C syntax. If I'm not mistaken, Typescript did not introduce a radical new syntax for declaring entities, only type annotations. I'm not familiar with Kotlin, but it doesn't appear that different from Java.

Kotlin has diverged from Java's syntax in some fairly significant ways, and a lot of those share similarity with the changes proposed in Carbon. You can see some of those in the [Kotlin documentation](https://kotlinlang.org/docs/basic-syntax.html).

> The example in the README uses C++ #include's rather than the more modern module syntax. That is somewhat similar to the way initial Rust presentations would emphasize how "atrociously" C++ behaved with examples using raw pointers instead of unique or shared pointers (I realize most existing C++ code uses #include's, but it seems fairer to do a comparison using the newer syntax).

[Carbon is currently targeting C++17 as its entry-point for interop](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/interoperability/philosophy_and_goals.md#interoperability-with-and-migration-from-existing-c-code), so C++20 modules are unavailable. That isn't to say that C++20 and beyond won't receive interop support, but it's not a priority in the initial roadmap.

> Last but certainly not least is the issue of error handling. I could not find a clear position but it seems that Carbon may not have try/catch. If so, is that seen as an improvement? How can Carbon then be a "successor" to C++?

[Carbon is still very much in design](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#how-complete-is-carbons-design). A lack of exception handling in the specification doesn't necessarily mean that there won't be exceptions: it just means that no one has looked into them just yet.

> Forgot to mention that there is already a "successor" language to C++ that, IIRC, has kept most of the C/C++ syntax intact (except for arrays). It's Walter Bright's D. It has modules and even design by contract features.

Please see [What alternatives did you consider? Why did they not work?](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#what-alternatives-did-you-consider-why-did-they-not-work). #1448 is our ticket to motivate someone writing an explicit section for why we don't think D works; you might like to subscribe to it so you get a notification once the FAQ is updated.

**Comment by jmafc** [comment]
0. Well, you have proven what I was going to write before: "It is very easy to say that you're going to have a "welcoming community", but the proof is in the pudding".  Closing the issue as "not planned" is *not* welcoming. BTW, if you click the question you mention in the FAQ (not the one in your text above) it doesn't redirect properly. Since I'm not welcome, I *will not* bother with GitHub discussions.
1. Have you read the "Most vexing parse issue" article? It says "the phenomenon was quite common in C++ until the introduction of uniform initialization in C++11". What is the point of referring to that now? Also, the first example is about a C-style cast? How many conscientious C++ programmers use C-style casts in their code in 2022?
2. I don't know much (or care) about Kotlin, but I don't think JetBrains developed it claiming it to be a "successor" to Java. Isn't Scala also a "successor" in that sense. I also agree with David Hunter suggestion that Carbon should drop its C++ succession claim (it sounds like princes battling it out for a throne).
3. The point is not about interoperability with some version of C++. My point is that if you're going to try to convince someone that something is better (or is going to be better) than something else, you should be making realistic comparisons.
4. Ah, but someone *has* looked into exceptions. The reason I brought it up, is because of https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/error_handling.md, which states "Carbon errors, unlike exceptions in C++ and similar languages, will *not* be propagated implicitly" (emphasis added). How can Carbon expect to interoperate with C++ if, in essence, it wants the programmer to pass the errors "up the chain" *explicitly*?

**Comment by cjdb** [comment]
Thank you for your reply. We use GitHub Issues to track things that can be resolved via a commit. That doesn't appear to be the case here, so we don't plan to continue discussing on this issue. As previously mentioned, we're more than happy to for you to engage in a GitHub Discussions thread or our Carbon Language Discord server.

I'm going to lock this issue to prevent further discussion here, but please bring your points of interest to the appropriate channels.
