### ISSUE TITLE
Add error handling goals to FAQ.

### ISSUE THREAD

**Issue by libbooze** [carbon-language/carbon-lang#1962]
C++ infamously has dual way of handling errors, people can look up Herb's [talk ](https://www.youtube.com/watch?v=ARYP83yNAWk)for details and Bjarne's [nope paper](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1947r0.pdf). 

So I think it would be interesting to know if you would be interested in lower cost exception, or you plan to support exceptions just as backward compat feature considering Google C++ style guide.
In particular do you prefer something like StatusOr for return type of functions that can fail...

P.S, I know error handling is a delicate topic because people have strong opinions, but still I think this should be discussed in FAQ.

**Comment by jonmeow** [comment]
I'm nudging this to leads to see if they want to provide an answer here. It's not obvious to me how focused they are on a particular decision at present. Note, even if the leaning is more towards a return type approach (which more language-level sugar support, similar to Rust), some degree of exception support around interoperability seems likely (so that decisions in this area have limited impact on calls between C++ and Carbon code).

**Comment by geoffromer** [comment]
See [this principle doc](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/principles/error_handling.md) for a partial answer: we intend for errors to be part of a function's return type, not a separate side channel like C++ exceptions. See also [p0301](https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0301.md) for more discussion of the underlying rationale.

**Comment by libbooze** [comment]
@jonmeow @geoffromer 
Thank you, that information is what I was interested in. Really hoping we will get a concise way of handling errors.
In future you may want to consider interop with https://en.cppreference.com/w/cpp/header/expected but that depends on when/if you will support interop with C++23.

**Comment by chandlerc** [comment]
(moving this out of the issue-for-leads as this wasn't revisited just effectively answered with the existing docs)
