### ISSUE TITLE
Run on linux !!!!

### ISSUE THREAD

**Issue by mohseniv** [carbon-language/carbon-lang#2090]
I wanted to know if I can run carbon on linux?

**Comment by jonmeow** [comment]
Please read [the status](https://github.com/carbon-language/carbon-lang#project-status) and [getting started](https://github.com/carbon-language/carbon-lang#getting-started) in /README.md

(note, if you need help, please use [discussions](https://github.com/carbon-language/carbon-lang/discussions) and not issues -- issues should be used for things which are fixed by a PR)
