### ISSUE TITLE
Does This language have any official website and discussion forum?

### ISSUE THREAD

**Issue by UsmanTariq2** [carbon-language/carbon-lang#2128]
Also wanted to ask if we can compile basic stuff. Last i checked there was no compiler

**Comment by jonmeow** [comment]
We're just using GitHub for the website right now -- that is, just https://github.com/carbon-language/carbon-lang. You'll find the README there includes notes about the [project status](https://github.com/carbon-language/carbon-lang#project-status); no compiler has been released, and you shouldn't expect a production-ready compiler for years. For more information, please read [the FAQ](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#what-is-carbons-status).

Note, GitHub does have a [discussion](https://github.com/carbon-language/carbon-lang/discussions) feature which we use (you'll see the tab for it above). Please use it for questions like this, rather than filing an issue; issues are better for when you have a problem that needs to be resolved, typically by a PR.
