### ISSUE TITLE
terminology for values that are guaranteed to live in memory and have a stable address versus values that are not

### ISSUE THREAD

**Issue by zygoloid** [carbon-language/carbon-lang#2242]
### Summary of issue:

Informally, there has been some use of the terms "l-value" and "r-value" to refer, respectively, to values that live in memory and have a stable address versus values that might not be stored in a stable location in memory. This is confusing, given that in C and C++, "lvalue" and "rvalue" are kinds of expression, not kinds of value, and refer to a static categorization of expressions based on what operations are permitted on those expressions. If we want to talk about something different than the traditional meaning, we should pick new, distinct terms, that differ by more than just the addition of a hyphen.

### Details:

One example where this has come up is in values returned from a function. A function call expression is an rvalue expression in C++ terminology (it can't be assigned to nor have its address taken), but people have been describing it as "returning an l-value" given that the returned object has an observable, stable address, as is exposed by `return var` declarations in the callee.

### Any other information that you want to share?

It would make sense to avoid using the terms "lvalue" and "rvalue" in Carbon's design with the C++ meanings, given that they too are confusing, because they are categories of expression but look like they're categories of value. Rust uses the terms "place expression" and "value expression" for these; we could adopt something similar. Explorer internally uses "var" and "let" to refer to the value category, and we could use "var expression" and "let expression" in the design documentation too.

**Comment by micttyl** [comment]
Dear readers
+ [Place Expressions and Value Expressions](https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions)

**Comment by tkoeppe** [comment]
Could you perhaps summarize/link to some background: What is a "value" in Carbon? What is a value other than the result of an evaluation [of an expression], and what is the distinction between "values" and "kinds of expression"?

**Comment by geoffromer** [comment]
> What is a "value" in Carbon? What is a value other than the result of an evaluation [of an expression], and what is the distinction between "values" and "kinds of expression"?

"The result of an evaluation of an expression" seems like a pretty good working definition of "value"; I'm not sure why you want something other than that. In particular, I think it effectively captures the distinction between the two: expressions are static elements of the source code of the program, whereas values occur dynamically, during execution of the program.

**Comment by tkoeppe** [comment]
> expressions are static elements of the source code of the program, whereas values occur dynamically, during execution of the program.

OK, that makes sense, but what is the need to distinguish the two: are there expressions that do not uniquely determine whether a value resulting from their evaluation has a stable address in memory?

**Comment by geoffromer** [comment]
Yes. For example, function call expressions are always r-values, because Carbon doesn't have references. However, depending on the function body, the actual returned value may have an address (for example, if it uses [`returned var`](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/control_flow/return.md#returned-var)).

**Comment by inbal2l** [comment]
> > expressions are static elements of the source code of the program, whereas values occur dynamically, during execution of the program.
> 
> OK, that makes sense, but what is the need to distinguish the two: are there expressions that do not uniquely determine whether a value resulting from their evaluation has a stable address in memory?

I don't know if it's of any help, but I recently gave a [talk](https://youtu.be/D52fZsQ9j4o) at C++Now2022 summarizing the topic and giving the up-to-date status of value categories in C++, including a brief intro to the latest C++23 feature - deducing this (which is an interesting topic by itself, reviewed in a great [talk](https://youtu.be/jXf--bazhJw) by Ben Deane (one of the feature's authors)).

**Comment by ghost** [comment]
> Dear readers
> + [Place Expressions and Value Expressions](https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions)

Rust language documentation details the types, uses, effects, and otherwise, of each expression in various contexts.

Solution to this issue is a study that consists of categorizing the types, uses, effects, and otherwise, of each expression in every possible context. Code language vocabulary already existing  in the industry should naturally advance _carbon-lang documentation_.

_Place expressions and value expressions_ are described briefly in Rust documentation like this:

_"Expressions are divided into two main categories: place expressions and value expressions; there is also a third, minor category of expressions called assignee expressions. Within each expression, operands may likewise occur in either place context or value context. The evaluation of an expression depends both on its own category and the context it occurs within._

_A place expression is an expression that represents a memory location. These expressions are paths which refer to local variables, static variables, dereferences (*expr), array indexing expressions (expr[expr]), field references (expr.f) and parenthesized place expressions. All other expressions are value expressions._

_A value expression is an expression that represents an actual value."_

**Comment by ghost** [comment]
> > What is a "value" in Carbon? What is a value other than the result of an evaluation [of an expression], and what is the distinction between "values" and "kinds of expression"?
> 
> "The result of an evaluation of an expression" seems like a pretty good working definition of "value"; I'm not sure why you want something other than that. In particular, I think it effectively captures the distinction between the two: expressions are static elements of the source code of the program, whereas values occur dynamically, during execution of the program.

Current expression precedence design terminology and variable design terminology, could be used to progressively solve this issue.

This issue appears to be bringing the future concept designs of globals and constants into current terminology.

Avoiding l-value and r-value terminology may be difficult until a later stage, considering expression precedence is a current leading design, while globals and constants are furture concepts.

docs/design/expressions/README.md

"Expressions are interpreted based on a partial precedence ordering."

docs/design/variables.md

"In this proposal, "variable" is defined as an identifier referring to a mutable value."

**Comment by jonmeow** [comment]
@zygoloid I've triaged this to a "leads question", but would you prefer something like a "design idea" label?

**Comment by zygoloid** [comment]
@chandlerc I believe your "Values, variables, and pointers" proposal will resolve this.

**Comment by josh11b** [comment]
#2006 has been accepted, and I believe resolves this question with the terms "value expressions," "reference expressions," and "initializing expressions" defined here: https://github.com/carbon-language/carbon-lang/blob/trunk/docs/design/values.md#expression-categories and https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p2006.md#values-objects-and-expressions

**Comment by chandlerc** [comment]
Agree with @josh11b and marking this as decided by the terminology in #2006 -- there was pretty good consensus on the terms we ended up with there.
