### ISSUE TITLE
Design Idea: "Build-once Run-anywhere" Feature

### ISSUE THREAD

**Issue by sepcnt** [carbon-language/carbon-lang#2411]
### Summary of issue:

**Will it worth to implement "Build-once Run-anywhere" feature for the Carbon standard library?**

### Details:

Will it be worthwhile to provide the "Build-once Run-anywhere" option for the Carbon standard library now that carbon aspires to provide scalable builds that function with existing C++ build systems?
The [cosmopolitan](https://github.com/jart/cosmopolitan) may be a great reference, in my opinion. However, Carbon STL might rely on the "compiler-rt" Runtime Library from LLVM rather than one created from scratch. I would love for Carbon to be easily compatible with practically any OS or architecture. It will also be very helpful for embedding development.

**Comment by chandlerc** [comment]
Personally, I think its too early to really contemplate making a real decision here.

Many of our users will want a native build and executable experience that matches what they currently have with C++ (rather than something like what [Cosmopolitan Libc](https://github.com/jart/cosmopolitan) you mentioned provides). I think at least initially while we're still in the experiment phase, we should focus on meeting those users where they are.

If we move out of the experiment phase, and start to get real user adoption where this is a highly desirable feature, then we should consider it and weigh it against any downsides it presents. But I suspect that's a few years away still, and so there isn't much we can do at this time.

**Comment by chandlerc** [comment]
FWIW, double checked with leads and I think we have consensus that this isn't something we can realistically dig into right now, but maybe worth asking again in a few years if/when Carbon is moving out an experiment. Thanks for the dropping the idea though!
