### ISSUE TITLE
Overcomplicated method declaration syntax

### ISSUE THREAD

**Issue by bugdea1er** [carbon-language/carbon-lang#2420]
### Summary of issue:

When Carbon language was introduced to CppNorth, the first declared drawback of C++ was the overcomplicated declaration syntax. Carbon suggested a simpler syntax, but it is still difficult for an outsider to understand.

### Details:

Consider the following example from the methods documentation:
```kotlin
class Point {
  // Method defined inline
  fn Distance[me: Self](x2: i32, y2: i32) -> f32 {
    var dx: i32 = x2 - me.x;
    var dy: i32 = y2 - me.y;
    return Math.Sqrt(dx * dx + dy * dy);
  }
  // Mutating method declaration
  fn Offset[addr me: Self*](dx: i32, dy: i32);
}
```

- Methods `Distance` and `Offset` use the class instance `me` which obviously always has the type of the containing class. The type specifier `Self` for the class instance value and `Self*` for the address of the class instance is rather useless and provide no additional info. It is proposed to remove the type specification for `me`:
  ```kotlin
  fn Distance[me](x2: i32, y2: i32) -> f32;
  fn Offset[addr me](dx: i32, dy: i32);
  ```

- `me` instead of `this` looks odd. `this` keyword appears in almost all the most popular OOP languages (C++ included), and replacing it with another without changing its meaning looks strange and can confuse programmers coming from other languages.
  ```kotlin
  fn Distance[this](x2: i32, y2: i32) -> f32 {
    var dx: i32 = x2 - this.x;
    var dy: i32 = y2 - this.y;
    return Math.Sqrt(dx * dx + dy * dy);
  }
  fn Offset[addr this](dx: i32, dy: i32);
  ```

- The `addr` keyword to designate a pointer to an existing instance of a class looks odd when the type system has a way of specifying a pointer with a star token `*`. (or ampersand token `&` for references).
  ```kotlin
  fn Distance[this](x2: i32, y2: i32) -> f32;
  fn Offset[this*](dx: i32, dy: i32);
  ```

**Comment by geoffromer** [comment]
[p0722](https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p0722.md) gives the rationale for requiring an explicit receiver type, and for using a keyword to mark pass-by-address (see #494 for additional background). The option of using `this` instead of `me` is discussed in #1382, which is still pending, so I'd suggest commenting on that PR if you don't think it adequately addresses that alternative.

Note that in order to be able to make progress, we [don't revisit decisions](https://github.com/carbon-language/carbon-lang/blob/trunk/docs/project/faq.md#when-do-we-revisit-decisions-or-reopen-discussions) unless we have new information that hasn't previously been considered.
