### ISSUE TITLE
What about the developer certificate?

### ISSUE THREAD

**Issue by shrek1402** [carbon-language/carbon-lang#2501]
### Summary of issue:

Every engineer, one way or another, is forced to choose for himself the profile that will be the main one for him. This profile is closely related to the main language it works with. But everyday tasks almost always leave their mark on the programmer, forcing him to use different parts of the language unevenly. As a result, he knows some parts better and some parts worse. He is able to apply some paradigms and patterns with his eyes closed, and for some it is necessary to open the documentation.

Take for example an engineer who writes on Android. Due to the specifics, he uses Java 6 most of the time and even being aware of all the innovations in Java 7 in practice, he encounters it less often. So it turns out that despite the inscription in the Java 7 resume, such a candidate may not always effectively perform tasks related to, say, Fork/Join or NIO2.

So it turns out that people who are almost invaluable in their workplace and feel the depth of their knowledge of the language themselves, sometimes fail even superficial interviews on their native topic with a bang. This is often the case with young professionals who really are not always familiar with their language to the fullest. The certificate also confirms that the specialist's knowledge is deep enough in all aspects of the language, and not only in multithreading or IO, or collections. The certificate, first of all, is an incentive to a deeper study of the language with which you work, as well as gives a more objective idea of what real knowledge a specialist in this field has.

I am sure that it would be a good practice to develop such a certificate so that every programmer using carbon owns such a certificate initially. It will be much easier to apply this practice than to force people to change their approach to work later.

**Comment by Jebeded** [comment]
This has nothing to do with the language. If you struggle to pass your interviews then pick up a book.

**Comment by jonmeow** [comment]
I think the Carbon Language project's more likely to push towards providing general educational materials in the future. Certifications are different: I wouldn't expect the project to provide them, although I'd expect that if Carbon succeeds, third-party organizations would offer certifications, as occurs for other programming languages today.

I do want to be clear though that I think people are going to learn in different ways, and sometimes get nervous in interviews. But the flip side to that point is, I'd trust an interview over a certificate because I don't know what a person actually learned to get a certificate, and I don't know how well they remember the material, but I can see how they think in an interview.

@Jebeded We want to treat each other courteously, even when we disagree. It's not an unreasonable request -- certifications can easily be found for most programming languages. I just don't think it's something Carbon project would get into.

**Comment by chandlerc** [comment]
I agree with @jonmeow but it's also too soon for us to even think about what educational materials would or wouldn't make sense. For now, our focus is documented in our roadmap: get ready for serious evaluation, and then try to evaluate and see if Carbon should leave the experiment phase. Closing as "not planned" for now.
