### ISSUE TITLE
To change the Carbon license for a more patent-friendly one like Boost or MIT

### ISSUE THREAD

**Issue by philippeb8** [carbon-language/carbon-lang#2693]
### Summary of issue:

The Carbon language currently uses the Apache License v2.0. The problem with this license is it dissolves the patent rights.

If Carbon was to use a more patent-friendly license like Boost or MIT then we could have a hybrid language that could be use for proprietary code and purely open-source purposes.

### Details:

For example, I do have a patented deterministic memory manager written in C++ that is very robust and efficient:
https://github.com/philippeb8/root_ptr

But it requires a proprietary source-to-source compiler to instrument existing code in order to inject the memory manager properly.

Since Carbon is still at the design phase, we could architect the language properly to add implicit parameters to functions, as well as implicit class members, compound statements instances and global scope ones. This way we could integrate the memory manager neatly.

But in order to do that Carbon would have to use the friendlier aforementioned license.

### Any other information that you want to share?

Usage example in C++:
[Superset_Manual.pdf](https://github.com/carbon-language/carbon-lang/files/11007084/Superset_Manual.pdf)

**Comment by chandlerc** [comment]
A meta note that everyone should be careful about when posting on this topic: _general_ discussions of legal issues are not on-topic for this forum, but we do need to be clear about how licenses impact this project. It is also important to not make legal claims when you are not a lawyer, and specifically a lawyer with expertise in the relevant area.

---

> The Carbon language currently uses the Apache License v2.0.

Tiny correction: we use the Apache License v2.0 with LLVM Exceptions.

> The problem with this license is it dissolves the patent rights.

Your statement is a legal claim that we shouldn't be making here, and it does not match the text of the license (for example "Grant of Patent License") or the FAQs from Apache: https://www.apache.org/foundation/license-faq.html#PatentScope

But I understand your general concern to be about being "patent-friendly":

> If Carbon was to use a more patent-friendly license like Boost or MIT

There is a post from the "Senior Commercial Counsel" for Red Hat that I think dives into how our license interacts with patents in a nice and accessible way: https://opensource.com/article/18/2/apache-2-patent-license

Notably, I think this paragraph really speaks to the concerns that you or others might have:
https://opensource.com/article/18/2/apache-2-patent-license#:~:text=Some%20contributors%20may%20be%20concerned%20that%20their%20contributions%20could%20lead%20to%20broad%2C%20expansive%20patent%20grants.

I don't think that the result is either "friendly" or "unfriendly" towards patents. I agree with this post that it "seems to strike a sensible balance" between the various parties' needs.

Of course, not everyone will agree, and an open source project under this license structure may not be the right place for them to contribute. However, I've checked with the leads and we remain comfortable with it. There are also a _very_ large number of contributors, both individuals and companies, that have been extremely successful contributing under the exact same license to the LLVM project. I think that is a strong demonstration that this is a viable and effective open source project license structure to use.

And given that we are using LLVM very heavily, their license would be extremely relevant for Carbon even if we attempted to diverge in some way.

---

However, I also want to address your specific desire:

> then we could have a hybrid language that could be use for proprietary code and purely open-source purposes.

To be clear, Carbon, with its current license, **can be used for proprietary code** in the exact same way that LLVM and Clang can and are heavily used by companies for their proprietary code. Nothing about our current license impacts this **use** of Carbon.

What Carbon's license does is require the **language** to be completely open-source. To be extremely clear: this is a feature and not a bug. Our goal is for the **language itself** to be 100% open-source.

That doesn't block people from building proprietary software with the language, including proprietary developer tools _for_ the language (IDEs, static analysis tools, etc), just like they do for C++ (and other languages, open-source or otherwise).

Which brings me to the details of your issue:

> For example, I do have a patented deterministic memory manager written in C++ that is very robust and efficient: [philippeb8/root_ptr](https://github.com/philippeb8/root_ptr)

Please don't make claims of what is or isn't patented here. That's a legal claim best discussed with lawyers.

That said, just as you've built something for C++, you're welcome to build something for Carbon.

But Carbon itself, the Carbon project and the language, are going to remain open-source and not in any way proprietary. So if you want to build a proprietary system for Carbon, you'll have to build it on your own.

Thanks,
-Chandler (on behalf of the leads)
