### ISSUE TITLE
add more primitive types and operations

### ISSUE THREAD

**Issue by jsiek** [carbon-language/carbon-lang#382]
Consider primitives in LLVM.

One goal is to provide enough primitives to be able to build libraries for common
things like strings, containers, etc.

Another goal is to be able to implement woff2.

**Comment by jonmeow** [comment]
I'm closing this out: there have been more operators added, and there's #767 to track numeric types. https://github.com/carbon-language/carbon-lang/wiki/Are-we-explorer-yet%3F has a bit more listed. We should probably have more specific issues where it makes sense to move forward, so that interested contributors have clearer direction on things to add.
