### ISSUE TITLE
compiling simple file fails

### ISSUE THREAD

**Issue by dasshiva** [carbon-language/carbon-lang#3991]
### Description of the bug:

On my system (Ubuntu 22.04 LTS), I cloned the repository and built the toolchain with no major problems.
Then to test the built compiler I put the following into a file called hello.carbon

`package test;
fn main() -> i32 {
   return 0;
}`
I compiled this with carbon compile and it went without errors.
However on trying to link with carbon link it failed with:
`/usr/bin/ld: cannot find -lstdc++: No such file or directory`

### What did you do, or what's a simple way to reproduce the bug?

Link an object file produced by the carbon compile command 

### What actually happened?

As stated above it was unable to find libstdc++

### Any other information, logs, or outputs that you want to share?

I eventually fixed the problem by symlinking `/usr/lib/x86_64-linux-gnu/libstdc++.so.6`  to `/usr/lib/libstdc++.so`.

I am posting this is as a solution for anyone who might be getting the same error.

**Comment by chandlerc** [comment]
We *just* added the `carbon link` command, and it definitely still has limitations. We're working to improve them.

In this case, it's relying on a system C++ standard library rather than bundling libc++ itself. That on our roadmap to fix in the linker, but it will take some time to get there.

You can likely work around this by installing `libstdc++` on your system in some way, but that's more of a workaround. Long-term, this won't be necessary.

Happy to help with workarounds here or in Discord, but I don't think we need a dedicated issue tracking this as we have a large body of work to get to the point where linking reliably doesn't hit this issue.
