### ISSUE TITLE
Where are the examples?

### ISSUE THREAD

**Issue by panjea** [carbon-language/carbon-lang#3996]
### Description of the bug:

Inside of `carbon-lang/examples` there is just a single file, sieve.carbon, and not much in there.
The front page docs say run this command:
`bazel run //explorer -- ./explorer/testdata/print/format_only.carbon`
But using my file manage in Linux, i can not quickly go to that folder, because its a hidden folder.
Why are the examples inside a hidden folder?

my workaround:
```
cd carbon-lang
open ./explorer/testdata
```

**Comment by chandlerc** [comment]
You've found the two examples we have.

Not sure what the problem is you're having running the explorer, that's a command that you can directly execute. And the `explorer/testdata` directory shouldn't be hidden? That may be a problem with your system, not the project.

Please re-open if you're having a specific issue running the explorer.
