### ISSUE TITLE
Parser testing for executable-semantics

### ISSUE THREAD

**Issue by geoffromer** [carbon-language/carbon-lang#428]
executable-semantics should have a lightweight way of unit-testing the parser directly, i.e. comparing the actual and expected ASTs produced by parsing a given string, without running any further semantic analysis, or the interpreter itself. The time is probably not ripe for this yet, since the AST representation is very much in flux, but I'm recording this now so we don't lose track of it.

**Comment by V1C70RYG0D** [comment]
After going through the Carbon explorer code base, I found that we can implement parser testing for executable-semantics by creating a test file with input strings and expected AST results, and writing a test function that uses the Parse function in syntax/parse.h to parse each input string and compare the resulting AST to the expected AST using Google Test assertions. I am planning to start working on this implementation soon.
if this issue is up?

**Comment by geoffromer** [comment]
Note that we already have the beginnings of an approach like that -- see [`explorer/syntax/unimplemented_example_test.cpp`](https://github.com/carbon-language/carbon-lang/blob/trunk/explorer/syntax/unimplemented_example_test.cpp) and the headers it includes. However, we have only a very limited set of matchers so far.

**Comment by chandlerc** [comment]
Closing explorer-specific issues as not-planned for now due to our decision to prioritize working on the toolchain over other implementation work in the near term: https://github.com/carbon-language/carbon-lang/blob/trunk/proposals/p3532.md
